### ISSUE TITLE
Difference between the original repo?

### ISSUE THREAD

**Issue by CaledoniaProject** [idaholab/Malcolm#100]
The original repos is still in active development, and I'm wondering what kind of feature is added in this repo. Can you explain on that?

**Comment by mmguero** [comment]
The idaholab and cisagov repositories are identical save for the links in documentation to the GitHub repositories and the labels in the docker images. I am the maintainer of both repositories and keep them in sync. There is no functional difference.

**Comment by CaledoniaProject** [comment]
Thanks!
