### ISSUE TITLE
enrich network traffic metadata with "device type"

### ISSUE THREAD

**Issue by Qiaoran-M** [idaholab/Malcolm#123]
Hi, I am a new Malcolm user and I have a question about the log enrichment. For the source and destination of logs, is Malcolm able to find out the device type (i.e. PLC, PC, workstation, etc)? I uploaded a pcap file to Malcolm earlier but didn't find much log information about the device type. 

Thanks for your help!

**Comment by mmguero** [comment]
See also idaholab/Malcolm#17
