### ISSUE TITLE
opensearch.keystore cannot be created, leading to Opensearch ConnectionError with old Python (3.6)

### ISSUE THREAD

**Issue by robcarson8** [idaholab/Malcolm#124]
Hello,
I'm having trouble running Malcolm.
Each time I do, I get the following error:

dashboards_1          |   log   [16:24:58.712] [error][data][opensearch] [ConnectionError]: connect ECONNREFUSED 172.22.0.5:9200

I followed all instructions shown here to the letter: [https://malcolm.fyi/docs/ubuntu-install-example.html#InstallationExample](url)

I also followed this issue #104 and tried everything you suggested, but have had no luck.

I've added my opensearch logs here:
[opensearch_logs.txt](https://github.com/idaholab/Malcolm/files/10023870/opensearch_logs.txt)

Thanks!

**Comment by mmguero** [comment]
Some how the services started without initializing the empty keystore file opensearch uses (`./opensearch/opensearch.keystore`), so when the services started Docker tried to helpfully create a directory instead.

Try this (in the Malcolm directory)

* `./scripts/wipe` to shut down and wipe the database (or `./scripts/stop` if you have some data in there already you want to preserve, but it sounds like that's not the case)
* `sudo chown -R user:user *` (in case some files got created with `root` permissions, which is possible with Docker)
* `rm -rf ./opensearch/opensearch.keystore ./logstash/certs/logstash.keystore` to clear out whatever's in the way of those keystore files existing correctly
* `./scripts/start` again to start things up

If things work correctly on startup, then, the `./opensearch/opensearch.keystore` should be created prior to the containers starting and get bound into the container correctly.

**Comment by robcarson8** [comment]
Hi,
I've followed those steps and I'm still getting the same error.

**Comment by robcarson8** [comment]
It seems like the container keeps restarting.
I doubt it's a RAM issue as I have the following memory assignment:

OPENSEARCH_JAVA_OPTS : '-server -Xms21g -Xmx21g -Xss256k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true'
      LS_JAVA_OPTS : '-server -Xms3500m -Xmx3500m -Xss1536k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true'

**Comment by mmguero** [comment]
I don't think it's a RAM error, either, the log you pasted showed pretty clearly that the issue is with the `opensearch.keystore` file.

Do `ls -l ./opensearch/opensearch.keystore`. If it shows a small file (~200 bytes) then it was created correctly on startup. If it shows a directory then it didn't get created correctly and was auto-created and bind-mounted into the container as a directory, which is causing opensearch to not start.

Go through the steps with the `wipe` and the `rm -rf ./opensearch/opensearch.keystore` again, then this time put a `-v` flag on the startup. Ctrl+C once the containers themselves start, then paste the output of what's before the containers starting here. That will give us a bunch of debug logs at the beginning and why the keystore file isn't created.

**Comment by robcarson8** [comment]
ls -l ./opensearch/opensearch.keystore gave the following:
total 0

This is the output from ./scripts/start -v:
[start-v_logs.txt](https://github.com/idaholab/Malcolm/files/10024258/start-v_logs.txt)

**Comment by mmguero** [comment]
The crux of it seems to be this:

```
['docker-compose', '-f', 'docker-compose.yml', 'ps', '-q', 'opensearch']() returned 0: ['/snap/docker/2285/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.', '  from cryptography.hazmat.backends import default_backend', '']
['docker-compose', 'exec', '-u', '1000:1000', '-w', '/usr/share/opensearch/config', 'opensearch', '/usr/share/opensearch/bin/opensearch-keystore', 'create']() returned 1: ['/snap/docker/2285/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.', '  from cryptography.hazmat.backends import default_backend', '']
Error processing command opensearch keystore: ['/snap/docker/2285/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.', '  from cryptography.hazmat.backends import default_backend', '']
```

I'd say try a newer version of python for docker-compose, I guess. 3.6 was EOL a year ago.

**Comment by mmguero** [comment]
I could give you a workaround, but you won't be able to send email alerts (that's what the keystore is for, I think):

Edit your docker-compose file and remove this line:

```
      - ./opensearch/opensearch.keystore:/usr/share/opensearch/config/opensearch.keystore:rw
```

Then go through the steps to wipe and restart. I think that ought to at least avoid the issue.

**Comment by robcarson8** [comment]
The workaround seems to have solved this issue, thank you!

**Comment by carl-3** [comment]
It looks like Docker keeps defaulting to an older version of python, but I can't seem to figure out how to point it to a newer version? I have 3.8 installed, but keep getting a warning about using Python 3.6 when attempting the start script.

**Comment by mmguero** [comment]
Not sure, depends on how it's installed and your distribution, I tink. You could run the scripts with directly with your version of python, e.g., `python3.8 ./scripts/whatever`.

**Comment by mmguero** [comment]
Totally not looking to dissuade you from the native install, but if for whatever reason your environment doesn't want to play nice with the requirements (python version, docker issues, whatever) you could always [download the ISO](https://malcolm.fyi/docs/download.html) and run it in a VM. Just an option.

**Comment by mmguero** [comment]
Whoa, sorry, full stop. Malcolm images are not built for ARM at all.

**Comment by carl-3** [comment]
Right, but this is a cloud VM from a corporate network.

**Comment by mmguero** [comment]
I think at this point we're debugging docker-specific issues. Your non-root user can run `docker info` without any errors? I haven't seen a permission denied error like that stopping containers before.

**Comment by mmguero** [comment]
I have set up Malcolm inside an AWS (c4.4xlarge, iirc) VM running amazonlinux-2, I have sort of a quick-and-dirty script I used to configure malcolm on that environment: https://github.com/idaholab/Malcolm/blob/main/scripts/demo/amazon_linux_2_malcolm_demo_setup.sh

**Comment by carl-3** [comment]
![Screen Shot 2023-03-28 at 11 21 00](https://user-images.githubusercontent.com/113935499/228305156-8a490c13-7db7-49b0-85c8-12ba12077fed.png)
yup, no issues with `docker info`

**Comment by mmguero** [comment]
I'm sorry,  I really don't know. I'd look into googling that "cannot stop container" "permission denied" errors. Best of luck.
