### ISSUE TITLE
Opensearch version_conflict_engine_exception

### ISSUE THREAD

**Issue by robcarson8** [idaholab/Malcolm#125]
I am getting the following error when running Malcolm:

dashboards_1          |   log   [19:11:09.060] [error][data][opensearch] [version_conflict_engine_exception]: [index-pattern:arkime_sessions3-*]: version conflict, required seqNo [21], primary term [1]. current document has seqNo [31] and primary term [1]

Here are the opensearch logs:
[opensearch_conflict_logs.txt](https://github.com/idaholab/Malcolm/files/10024992/opensearch_conflict_logs.txt)

**Comment by mmguero** [comment]
That particular error message can be ignored, it's not fatal and should not affect how data is ingested or visualized.
