### ISSUE TITLE
support Malcolm deployment with Kubernetes 

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#149]
There have been requests from both the community and project funding sources to get Malcolm running in Kubernetes (K8s). This feature is to track the research, design and development to do so. We may break this out into sub-issues if it makes sense to do so.

Malcolm currently runs as a cluster of containers orchestrated by [Docker Compose](https://github.com/idaholab/Malcolm/blob/main/docker-compose.yml). Since it's already containers-based, we're hoping the K8s translation won't be too onerous. This will be @mmguero's and @piercema's first foray into K8s, so we'll be learning as we go. I've done some very basic "Hello, World!"-type stuff in [K3s](https://k3s.io/) before, which I think might be useful as a development/testing tool as we figure this out.

Perhaps the tool [kompose](https://github.com/kubernetes/kompose) ([docs](https://kompose.io/)) could help?

Some of the questions we'll need to address as we go:

* How to maintain in revision control the existing docker-compose solution for single-node installations vs. the K8s solution
* Malcolm uses various scripts external to the containers themselves as [wrappers](https://github.com/idaholab/Malcolm/blob/main/scripts/control.py) around docker-compose and for setting up things like static [configuration](https://github.com/idaholab/Malcolm/blob/main/scripts/install.py) and [authentication](https://github.com/idaholab/Malcolm/blob/76525caadfc7b0c27d0e7764a388559c18f63903/scripts/control.py#L717). We need to figure out how/when this configuration will be done, as well as...
* How to handle the bind mounts: Malcolm's configuration files as well as the OpenSearch database, PCAP files, Zeek log files., self-signed certificates, certificates for trusted CA sources, etc., etc., etc. are all done via Docker [bind mounts](https://idaholab.github.io/Malcolm/docs/contributing-local-modifications.html#Bind). This is obviously a very single-node mentality, so we need to figure out how to use things like K8s [ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) (also [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/)) and [Volumes](https://kubernetes.io/docs/concepts/storage/) (also [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/) and [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/)) to do the same thing (while, of course, preserving the existing model as well for single-node installs).
* all access to Malcolm's web-based interfaces are done through [NGINX](https://github.com/idaholab/Malcolm/blob/main/nginx/nginx.conf) in a [container](https://github.com/idaholab/Malcolm/blob/76525caadfc7b0c27d0e7764a388559c18f63903/docker-compose.yml#L1082) ([image](https://github.com/idaholab/Malcolm/blob/main/Dockerfiles/nginx.Dockerfile)). Kubernetes is of course going to be doing its own proxying of HTTP(S) connections. How will these two things work together? Will K8s just sit in front of the nginx containers on the nodes and handle the requests rather than NGINX itself [surfacing the ports](https://github.com/idaholab/Malcolm/blob/76525caadfc7b0c27d0e7764a388559c18f63903/docker-compose.yml#L1107-L1109)?

There will certainly be other questions and answers we come across, which will be documented here or in other GitHub issues referencing this one as we go.

**Comment by mmguero** [comment]
There are lots of blogs/documents online with opinions about K8s manifests with Terraform vs. Helm vs. Kustomize vs. ???? so we should look into the pros/cons of these options and figure out what makes the most sense for us.

**Comment by mmguero** [comment]
We're having an internal call today with a colleague who's got a lot of experience with K8s, tracking the Q/A and agenda here:

1. We'll give a brief architectural overview of how Malcolm runs today with `docker-compose`, focusing on mainly container interaction, volume mounts, how the containers' interfaces are proxied, authentication, top-level stuff like that.
    * docker-compose
        - [docker-compose file](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml)
        - [Docker bind mounts](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/contributing-local-modifications.md)
    * NGINX
        - [service in docker-compose file](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L1009-L1048)
        - [nginx.conf](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/nginx/nginx.conf)
        - [authentication](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/authsetup.md)

1. We suspect a lot of thought will have to go into making the right choices when it comes to translating our docker bind mounts into this new paradigm. We'll organize the various types of data used by the containers into categories (i.e., database, log/PCAP storage, config files) and ask for guidance on what the right mechanism in Kubernetes is for us to do the same things (while, of course, preserving the existing model as well for single-node installs).
    * Kubernetes concepts
        - [storage mechanisms](https://kubernetes.io/docs/concepts/storage/)
        - [configuration mechanisms](https://kubernetes.io/docs/concepts/configuration/)
    * environment variables
        - via [`docker-compose.yml`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L5)
            + either hand-edited or set via [`install.py`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/scripts/install.py#L854)
        - via `env_file`
            + [`netbox.env`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/netbox/env/netbox.env.example) used by [logstash](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L472) and [netbox](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L887)
            + [`redis.env`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/scripts/control.py#L1327-L1328) used by [`netbox-redis`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L941)
            + [`redis-cache.env`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/scripts/control.py#L1323-L1325) used by [`netbox-redis-cache`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#968)
            + [`postgres.env`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/scripts/control.py#L1317-L1320) used by [`netbox-postgres`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L918)
            + `auth.env` used by [arkime](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L548) and [upload](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L793)
    * [OpenSearch (database) indices](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L393) and [snapshots](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L394)
        - [Run OpenSearch using Helm](https://opensearch.org/docs/1.0/opensearch/install/helm/) on opensearch.org
        - [github.com/opensearch-project/helm-charts](https://github.com/opensearch-project/helm-charts)
    * [bind mounts](https://docs.docker.com/storage/bind-mounts/)
        - capture artifacts
            + `./pcap/` (sometimes subdirectory `./pcap/upload/`)
                * used by `arkime`, `zeek`, `suricata`, `pcap-monitor` and `upload`
            + `./zeek-logs/` (sometimes subdirectories `./zeek-logs/upload/`, `./zeek-logs/live/`, `./zeek-logs/extract_files/`, `./zeek-logs/current/`)
                * used by `filebeat`, `zeek`, `zeek-live`, `file-monitor`, `pcap-monitor`
            + `./suricata-logs/`
                * used by `filebeat`, `suricata`, `suricata-live`,
            + `./arkime-logs/` and `./arkime-raw/`
                * these are only used by Arkime and could probably go away or turned into a regular ephemeral volume mount
        - configuration files and directories
            + read-only
                * `./nginx/ca-trust/`
                    - contains trusted CA certificates
                    - used by all Malcolm services on containers' start
                * `./.opensearch.primary.curlrc` and `./.opensearch.secondary.curlrc`
                    - stores credentials for primary and secondary [remote opensearch instances](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/opensearch-instances.md#authentication-and-authorization-for-remote-opensearch-clusters) (when not managed locally by Malcolm)
                    - used by `opensearch`, `dashboards`, `dashboards-helper`, `logstash`, `filebeat`, `arkime`, `pcap-monitor`, `api` (any services that need to connect to OpenSearch)
                * `./logstash/maps/malcolm_severity.yaml`
                    - [customizable event severity mappings](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/severity.md) used by `logstash`
                * `./logstash/certs/`
                    - contains (usually self-signed) `ca.crt`, `server.crt` and `server.key` for the server side of `filebeat` -> `logstash` communications
                * `./filebeat/certs/`
                    - contains (usually self-signed) `ca.crt`, `client.crt` and `client.key` for the client side of `filebeat` -> `logstash` communications
                * `./nginx/certs/`
                    - contains (usually self-signed) key and certificate files for securing connections to the web UI via [TLS](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/authsetup.md#tls-certificates)
                * `./nginx/nginx_ldap.conf`
                    - connection parameters for [LDAP authentication](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/authsetup.md#lightweight-directory-access-protocol-ldap-authentication)
                * `./net-map.json`
                    - customizable CIDR [subnet name mapping](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/host-and-subnet-mapping.md#HostAndSubnetNaming), used by `logstash`, `name-map-ui` and `netbox`, somewhat deprecated now
                * `./suricata/rules/`
                    - user-defined Suricata rule files are read from this directory and used by `suricata` and `suricata-live`
                * `./yara/rules/`
                    - user-defined YARA rule files are read from this directory and used by `file-monitor`
                * `./netbox/config/` and `./netbox/media/`
                    - persistent configuration, reports, scripts and media files used by [`netbox`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/asset-interaction-analysis.md)
                * `./netbox/postgres/`
                    - postgresql database files used by `netbox-postgres`
                * `./netbox/redis/`
                    - redis cached document storage used by `netbox-redis`
            + writable
                * `./opensearch/opensearch.keystore`
                    - used to store authentication for [email sender accounts](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/alerting.md#AlertingEmail)
                * `./zeek/intel/`
                    - used by `zeek` and `zeek-live`, updates to [Zeek intel feeds](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/zeek-intel.md#ZeekIntel) are written to and read from this directory
                * `./htadmin/metadata` and `./htadmin/config.ini`
                    - used by `htadmin` for [local account management](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/authsetup.md#AuthBasicAccountManagement)
                * `./nginx/htpasswd`
                    - used by `htadmin` and `nginx-proxy` for [local account management](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/authsetup.md#AuthBasicAccountManagement)
    * [named volumes](https://docs.docker.com/storage/volumes/)
        - `nginx-log-path`
            + used by `nginx-proxy` (which produces acess and error logs) and `filebeat` (which consumes them)

1. Malcolm today has some scripts that are run on the host machine (outside of the containers) for configuration (asking the user for options and storing them in environment variables in the docker-compose file), setting up authentication and runtime operations (stop, start, restart, etc.). We'd like to go over a few of these and see what parts of them make sense to map over into a K8s-focused environment vs. which ones don't necessarily apply outside of docker-compose.
    * [`control.py`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/scripts/control.py)
        - configuration-related operations
            + [configure authentication](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/scripts/control.py#L840)
                * input username and password, use openssl to hash and store in `auth.env` and `htpasswd`
                * ask some questions about [LDAP authentication](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/authsetup.md#lightweight-directory-access-protocol-ldap-authentication)
                * populate `./htadmin/config.ini`
                * generate self-signed [TLS certificates](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/authsetup.md#tls-certificates)
                * input and save credentials for remote [opensearch instances](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/opensearch-instances.md#authentication-and-authorization-for-remote-opensearch-clusters)
                * input and save credentials for [email sender accounts](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/alerting.md#AlertingEmail)
                * generate random keys for netbox-related environment env. files
        - runtime-related operations
            + start
            + restart
            + stop
            + wipe
            + logs
            + status
            + netbox [backup](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/scripts/control.py#L277) and [restore](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/scripts/control.py#L324)
                * uses `docker-compose exec` to run commands inside the `netbox` and `netbox-postgres` containers to save the contents of NetBox's postgresql database and saved media files to tarballs
    - `install.py`, particularly the [`--configure`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/scripts/install.py#L327) option
        + [asks](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docs/ubuntu-install-example.md) a lot of configuration questions of the user then store the answers as environment variables in [`docker-compose.yml`](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose-standalone.yml#L5)
        + the other parts of this script (outside of the `--configure` actions) are for system configuration, installing docker, etc., which probably don't apply to a Kubernetes installation

1. There are a fair amount of tools out there dealing with managing Kubernetes deployments: things like Helm, Terraform, others we might not even be aware of, etc. We'd like to get best practices for incorporating these tools into what we do. For what it's worth, we've had some customer requests specifically for Helm charts, and with the number of services Malcolm has I think that's probably the way to go, at least in part. Some resources:
    * OpenSearch and OpenSearch Dashboards
        - [Run OpenSearch using Helm](https://opensearch.org/docs/1.0/opensearch/install/helm/) on opensearch.org
        - [github.com/opensearch-project/helm-charts](https://github.com/opensearch-project/helm-charts)

**Comment by mmguero** [comment]
## Services for which Kubernetes manifests need to be developed

See **support Malcolm deployment with Kubernetes** [idaholab/Malcolm#149](https://github.com/idaholab/Malcolm/issues/149)

"Core services" are listed earlier in the list (i.e., we should probably approach the services roughly in this order).

* nginx-proxy
* opensearch
    - This is more complicated if we do OpenSearch in the container vs. [a remote instance](https://idaholab.github.io/Malcolm/docs/opensearch-instances.html#OpenSearchInstance). My recommendation is to do early development of this container with a remote instance (see the corresponding [`docker-compose.yml` section](https://github.com/idaholab/Malcolm/blob/0c14303f242ce1bae7e48b30ca7234c996930008/docker-compose-standalone.yml#L46-L68)) and then come back to it. We can still do the service/container with the `OPENSEARCH_LOCAL` variable set to `false`, which will cause the [`service_check_passthrough.sh`](https://github.com/idaholab/Malcolm/blob/main/shared/bin/service_check_passthrough.sh) script to get run at startup instead of the actual OpenSearch service. Note that [this requires](https://idaholab.github.io/Malcolm/docs/opensearch-instances.html#OpenSearchAuth) [LDAP authentication](https://idaholab.github.io/Malcolm/docs/authsetup.html#AuthLDAP), or to use basic authentication but ensure the accounts and passwords match on Malcolm and the remote OpenSearch instance.
* dashboards
* upload
* pcap-monitor
* arkime
* api
* dashboards-helper
* zeek
* suricata
* file-monitor
* filebeat
* freq
    - This one really doesn't have many dependencies on other services, so it could be done whenever.
* logstash
* name-map-ui
* netbox-redis
* netbox-redis-cache
* netbox-postgres
* netbox
* htadmin
    - Leaving this for towards the end since if we're using remote OpenSearch we'd be using LDAP anyway, and even if not we can use auth_setup to set a username/password. At the point this is done we'll no longer be able to use `configmap` for `nginx/htpasswd` (and `htadmin/config.ini`) as they'll need to be read/write.
* pcap-capture
    - Not sure what live capture looks like at all in this scenario: what would the capture interface be? So leaving this to the very end.
* zeek-live
    - See note for `pcap-capture`.
* suricata-live
    - See note for `pcap-capture`.

**Comment by mmguero** [comment]
We need to research how to deal with rlimit/memlock/ulimit/file handle limit stuff. Opensearch has some very important tuning considerations and we have to figure out what to do in k8s world for that. See https://github.com/kubernetes/kubernetes/issues/3595

**Comment by mmguero** [comment]
Hmmm, a lot from my previous comment doesn't work inside of a docker container.

Also, [cap_add](https://www.weave.works/blog/container-capabilities-kubernetes/)

**Comment by mmguero** [comment]
Here's where we're at right now:

* All containers are configured to start and seem to be at least nominally working, with the exception of
    * htadmin
    * all live capture-related containers (pcap-capture, zeek-live, suricata-live)
    * opensearch

Here are some things we still have to work on:

* htadmin
* opensearch
* inotify issue
    * A lot of the code in Malcolm that deals with processing PCAP, processing logs, processing extracted files, relies on inotify (here is [one good example](https://github.com/idaholab/Malcolm/blob/07389fb00e5699dbce2833b77eb559b816716443/pcap-monitor/scripts/watch-pcap-uploads-folder.sh#L14)). However, with a PersistentVolume over NFS, it doesn't appear we're getting those events. That would make sense, as from what I understand inotify is a kernel thing and it may not be propogated over NFS. We need to figure out if this is something we can "fix" magically and make work everywhere with all types of persistentvolumes (which, unfortunately, I kind of doubt) or come up with something else (probably some kind of polling). Grepping `inotify` in the source code will show where we need to do it.
* htadmin
   * the way things sit now, a local `./nginx/htpasswd` file is being created by `control.py`'s `auth_setup` and a read-only [configmap](https://github.com/mmguero-dev/misc-debug/blob/24b3a8995dcac143f5026178e5beb6f69d51320b/k3s-debian-vagrant/malcolm-control.sh#L77) is created and [mounted](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/kubernetes/99-nginx-proxy.yml#L60-L61) and [used](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/nginx/nginx_auth_basic.conf#L2) by nginx. However, the htadmin container is for dynamically creating and modifying usernames/passwords, so the `htpasswd` file needs to be read-writeable and shared across both the `htadmin` and `nginx` containers. What we've proposed is that the original `htpasswd` file is created and initially put into the `nginx` container this way, but then just used to "bootstrap" and in the [nginx container entrypoint](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/nginx/scripts/docker_entrypoint.sh) it can be checked against a location in the [`config` PeristentVolume](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/kubernetes/01-volumes.yml#L124-L163). If the persistentvolume one exists, then that's the one that will be used and take precedence. If not, the configmap `htpasswd` will be copied into the persistenvolume and then that will be used from then on out. We would also add an `export` button to the htadmin interface to allow them to save/export changes to the `htpasswd` file.
* OpenSearch
    * as mentioned above, currently we're testing with an external OpenSearch cluster. We need to figure out what it'll take to get it running nicely in kubernetes. Getting it turned on should be easy, but getting the underlying system tuned is sort of a mystery for me with Kubernetes (see [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/master/setting-system-settings.html) and [opensearch](https://opensearch.org/docs/latest/install-and-configure/install-opensearch/index/#important-settings) docs). We need to figure that out.
* Uploading large PCAP files
    * docker-based Malcolm can handle uploading quite large PCAP files (relevant settings can be found in [nginx.conf at the top](https://github.com/idaholab/Malcolm/blob/07389fb00e5699dbce2833b77eb559b816716443/nginx/nginx.conf#L14-L27) and [nginx.conf in the /upload section](https://github.com/idaholab/Malcolm/blob/07389fb00e5699dbce2833b77eb559b816716443/nginx/nginx.conf#L103-L122) as well as in the configuration of the [upload container](https://github.com/idaholab/Malcolm/blob/07389fb00e5699dbce2833b77eb559b816716443/file-upload/nginx/sites-available/default) and in its [PHP configuration](https://github.com/idaholab/Malcolm/blob/07389fb00e5699dbce2833b77eb559b816716443/file-upload/php/php.ini#L46)). That's not working yet with [Kubernetes](https://github.com/idaholab/Malcolm/blob/95fb337d6c5cfafa3653a97e7cc5f5b2883bf25e/kubernetes/00-ingress.yml#L7-L17). We need to figure out the proxy buffering/chunking for large file upload.
* Script consolidation
    * I don't think Malcolm's `install.py` script is going to install Kubernetes for anybody, but the `install.py --configure` part certainly could and probably should ask for relevant settings and/or skip settings that are docker-compose specific if they want to do a Kubernetes deployment. We've consolidated the environment variable configuration (see the [config directory](https://github.com/idaholab/Malcolm/tree/592182f951df94b37481340b698486f91e0b4362/config), [control.py](https://github.com/idaholab/Malcolm/blob/95fb337d6c5cfafa3653a97e7cc5f5b2883bf25e/scripts/control.py#L254-L274) and [install.py](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/scripts/install.py#L881-L1220) and the removal of these values from [docker-compose.yml](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/docker-compose-standalone.yml#L3-L5)).  We need to see how else to tweak the scripts to facilitate a Kubernetes deployment. I think minimally we could have the control.py script's `start`, `stop`, etc., reference call the appropriate `kubectl --kubeconfig whatever.yaml` (with the yaml file they provide) using either kubectl or the corresponding [python library](https://github.com/kubernetes-client/python) and start/stop/logs/status/etc. Malcolm that way. We've been using this [testing script](https://github.com/mmguero-dev/misc-debug/blob/24b3a8995dcac143f5026178e5beb6f69d51320b/k3s-debian-vagrant/malcolm-control.sh) for starting and stopping Malcolm in Kubernetes, some of that will need to be adopted for creating configmaps, etc.
* Documentation
   * A fair amount of documentation needs to be written. Also, any documentation referencing the [existing environment variables](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/docs/malcolm-config.md) needs to be updated (see above where in *Script consolidation* where I talk about environment variables). We should particularly document any gotchas we've run into, including SSL passthrough (which we learned works as long as you're defining and accessing things in the ingress by host name).
* User-defined persistent volumes
   * while we're testing with some [local nfs volumes](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/kubernetes/01-volumes.yml), the user will need to define whatever kind of persistentvolume backing storage as they want. I'm not sure the best way to do this. My guess is that the easiest thing to do will be to require them to create and populate the contents of that `01-volumes.yml` file themselves, and that they must define, using the same names, the volumes and volume claims in that example. Then those can get created and we can use them by those names.
* Live capture
   * does this even make sense in a kubernetes environment? I kind of don't think so? Not sure. Maybe we just leave these turned off, (see [pcap-capture](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/kubernetes/20-pcap-capture.yml#L30-L32), [zeek-live](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/kubernetes/21-zeek-live.yml#L37-L38), [suricata-live](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/kubernetes/22-suricata-live.yml#L37-L38)).
* opensearch keystore
    *  in order to store creds for an [email alerter](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/docs/alerting.md#AlertingEmail), [opensearch.keystore](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/scripts/control.py#L766-L767) is [created](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/scripts/control.py#L1311-L1315) and [populated](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/scripts/control.py#L76) by `control.py` at startup. It then has to be mounted [into the container](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/docker-compose-standalone.yml#L32). I think this would work okay with a [configmap](https://github.com/mmguero-dev/misc-debug/blob/24b3a8995dcac143f5026178e5beb6f69d51320b/k3s-debian-vagrant/malcolm-control.sh#L94-L97) but what about the initial creation? Today that's done inside of a container (either by [docker run](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/scripts/control.py#L173) when Malcolm isn't started up yet or [docker-compose exec](https://github.com/idaholab/Malcolm/blob/592182f951df94b37481340b698486f91e0b4362/scripts/control.py#L139) if it is). Is there some way we can pass these secrets in to the container itself for the keystore to be created at the entrypoint, or do we still have to have them create it beforehand?

That's all that's off the top of my head right now. A lot of progress has been made but there's still a lot to do.

**Comment by piercema** [comment]
Opensearch: For a very simply, non-scalable implementation we can mimic the docker container. 

Scalable instances seem to require the use of Helm charts or the [OpenSearch Kubernetes Operator repo](https://github.com/Opster/opensearch-k8s-operator). See documentation here(https://opensearch.org/docs/2.0/clients/k8s-operator/)

**Comment by mmguero** [comment]
Getting [very close](https://github.com/idaholab/malcolm/issues?q=is%3Aissue+is%3Aopen+kubernetes) to a basically working kubernetes workflow for Malcolm.

**Comment by mmguero** [comment]
Initial work for kubernetes is done. Some "kubernetes next steps" issues have been logged for things going forward.
