### ISSUE TITLE
Editing Arkime defaults 

### ISSUE THREAD

**Issue by Mechaniquake** [idaholab/Malcolm#154]
Hi, I'm fairly new to the interface and trying to capture arp traffic with Arkime as per [this](https://github.com/arkime/arkime/issues/1159) feature request on the Arkime GitHub page. I want to add a line to the config file but can't find the location of that folder.

I'm using the Malcolm pre-built iso with another VM running Hedgehog. I've been following all the docs and YouTube tutorials and have found them very useful.

**Comment by mmguero** [comment]
Here's what you'd need to do:

1. Grab the Arkime `config.ini` [corresponding to your Malcolm version](https://raw.githubusercontent.com/idaholab/Malcolm/main/arkime/etc/config.ini) from the Malcolm GitHub repository and copy it to your Malcolm installation directory as `./arkime/etc/config.ini`
2. Edit that `./arkime/etc/config.ini` file adding whatever line it is you need to add
3. Edit `docker-compose.yml` and find the `arkime` section under `services`, then add the following line to its `volumes` section (like [this](https://github.com/idaholab/Malcolm/blob/9fa4c78bd1cd89e3e807618f6de800506c19891c/docker-compose.yml#L594):
    *`      - ./arkime/etc/config.ini:/opt/arkime/etc/config.orig.ini:ro`
4. Stop Malcolm (`./scripts/stop`) and start it back up again (`./scripts/start`)

When Arkime starts back up again, your local copy of `config.ini` should be [bind-mounted](https://idaholab.github.io/Malcolm/docs/contributing-local-modifications.html#Bind] into the Arkime container.

Best of luck.

**Comment by mmguero** [comment]
I'm glad you were able to get things set up and that the YouTube tutorials and documentation were helpful. We're trying to learn more about how the community uses Malcolm. If you have a few minutes to fill out [this survey](https://forms.gle/JYt9QwA5C4SYX8My6) about how you use it we'd sure appreciate it.
