### ISSUE TITLE
Integrate Sigma rules via OpenSearch Security Analytics

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#162]
How could Malcolm integrate sigma?

[Sigma](https://github.com/SigmaHQ/sigma):

> Sigma is a generic and open signature format that allows you to describe relevant log events in a straightforward manner. The rule format is very flexible, easy to write and applicable to any type of log file. The main purpose of this project is to provide a structured form in which researchers or analysts can describe their once developed detection methods and make them shareable with others.
> 
> Sigma is for log files what Snort is for network traffic and YARA is for files.

* [OpenSearch Security Analytics](https://opensearch.org/docs/2.4/security-analytics/index/) plugin uses Sigma. Malcolm actually includes this plugin just because it's part of OpenSearch, but we're not really doing anything with it.
* I think Elastic SIEM does as well (?)

**Comment by mavam** [comment]
The current sigmac is going to be deprecated by the end of the year. If you start with this now, I would highly recommend going the pySigma route. That said, I don't know whether the [Elasticsearch backend](https://github.com/SigmaHQ/pySigma-backend-elasticsearch) also supports OpenSearch.

You could also consider writing a transpiler, as we did in [VAST](https://vast.io/docs/understand/language/frontends/sigma).

**Comment by mmguero** [comment]
Thanks for the suggestion!

**Comment by mmguero** [comment]
* [Sigma taxonomy](https://github.com/SigmaHQ/sigma-specification/blob/main/appendix/sigma-taxonomy-appendix.md)
    * for mapping, note how [product](https://github.com/SigmaHQ/sigma-specification/blob/main/appendix/sigma-taxonomy-appendix.md#zeek) and service seem pretty much to line up with our `event.provider` and `event.dataset`.
* [log types and mapping](https://opensearch.org/docs/latest/security-analytics/#log-types)

**Comment by mmguero** [comment]
See [this thread](https://forum.opensearch.org/t/null-cannot-be-cast-to-non-null-type-creating-a-detector/21786) for an issue I'm having.

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/475)
