### ISSUE TITLE
migrate away from DockerHub container registry

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#163]
Docker (the company) [has announced](https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf) then are "sunsetting free teams" plans, which I am [pretty sure](https://hub.docker.com/u/malcolmnetsec) will affect Malcolm.

See docker/hub-feedback#2314

We have a few options:

* start using [idaholab](https://hub.docker.com/u/idaholab) namespace (e.g., from `docker.io/malcolmnetsec/zeek` to `docker.io/idaholab/malcolmnetsec/zeek`)
* start using [GitHub's container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) (e.g., from `docker.io/malcolmnetsec/zeek` to `ghcr.io/idaholab/malcolmnetsec/zeek`)
* investigate other registries with free plans (e.g., [quay.io](https://quay.io/))

My instinct is to go with GitHub (ghcr.io) as we're already using GitHub for source code, for issue and project tracking, and CI actions.

There are issues, both technical and social, about how to handle this. For example, what about the existing malcolmnetsec namespace? We want to avoid squatters as this is a serious security concern, although it's more on Docker to answer this.

**Comment by Vad1mo** [comment]
If, for some reason, the Docker-Sponsored Open-Source Program isn't working out, we are happy to help you out. We operate a Harbor-based [container registry as a service ](https://container-registry.com/)that has many benefits over most of the other registries out there.

There are also features regarding containerized image distribution, that might be valuable too as well.

Don't underestimate the value of owning and controlling your data, it is easier to migrate if the domain is under your control.

**Comment by mavam** [comment]
> My instinct is to go with GitHub (ghcr.io)

We are going there as well. It works well both as registry and cache, which we used extensively in the past.
