### ISSUE TITLE
Unable to upload pcap file

### ISSUE THREAD

**Issue by carl-3** [idaholab/Malcolm#167]
# 🐛 Summary #

Unable to upload pcap file via https://localhost/upload

## To reproduce ##

1. Navigate to https://localhost/upload
2. Select "Add files..."
3. Select desired PCAP and select "Open"
4. Click "Start Upload" (or click "Start") 
5. Notice that the previously selected PCAP/PCAPNG file has now disappeared. 

## Expected behavior ##

I expected that I would be able to upload and then analyze a file using the GUI.

## Any helpful log output or screenshots ##

It looks like the problem stems from opensearch crashing. 
![Screen Shot 2023-03-27 at 11 53 16](https://user-images.githubusercontent.com/113935499/228047057-37032ace-f1fa-4644-9ad5-d3adeb1803af.png)

**Comment by carl-3** [comment]
Thanks for the thorough response!! 

Running into a problem where I get a permission denied error when trying to run the 'wipe' script, and then when trying to run it as sudo get an exception saying wipe shouldn't be run as sudo. Thoughts?

**Comment by mmguero** [comment]
Some file or directory got created with root permissions that shouldn't have been. Making *sure* you're in the Malcolm directory, run

```
sudo chown -R user:user *
```

replacing `user` with your username.  This will run as root (`sudo`) a recursive change ownership operation (`chown -R`) to change ownership to your user and group (`user:user`) all of the file in this directory (`*`).

Then do the wipe, etc.

**Comment by carl-3** [comment]
`sudo chown -R user:user *` seemed to work fine, but still getting a permission denied error when running `./scripts/wipe`. from the `Malcolm` directory

**Comment by mmguero** [comment]
Can you run `./scripts/wipe -v` to enable verbose output and paste it here?

**Comment by carl-3** [comment]
How would I ensure that I run the set up as a regular user and not as root?

**Comment by mmguero** [comment]
Just make sure you're not using `sudo` or `su`. Before you run it, do something like this to verify you're `johndoe` (or whatever your username is) instead of `root`.

```
$ whoami
johndoe

$ ./scripts/install.py -c
...

$ ./scripts/auth_setup
...
```

Actually, before you go too much further: something about the error message sparked a memory I had and I remembered this bug: idaholab/Malcolm#124.

It looks like you're using python 3.6, which is EOL well over a year ago. See the comment at the bottom of the issue idaholab/Malcolm#124. This old EOL version of pythopn 3 is probably the original root of the problem here.

**Comment by carl-3** [comment]
Oh that's awkward. I'll see if updating python fixes things. Thanks for the help!

**Comment by carl-3** [comment]
> Just make sure you're not using `sudo` or `su`. Before you run it, do something like this to verify you're `johndoe` (or whatever your username is) instead of `root`.

Thought I'd let you know that the quick start says to use sudo when installing malcolm. 

![Screen Shot 2023-03-28 at 21 03 11](https://user-images.githubusercontent.com/113935499/228407363-618c592f-1eae-4287-8e92-aba146e493c7.png)

**Comment by mmguero** [comment]
Correct, you run sudo when doing the initial `install.py`. Then, during the installation:

```
Add a non-root user to the "docker" group?: y   

Enter user account: user
```

Then, as the [documentation](https://malcolm.fyi/docs/ubuntu-install-example.html#InstallationExample) also says:

> If you are configuring Malcolm from within a git working copy, install.py will now exit. Run install.py again like you did at the beginning of the example, only remove the sudo and add --configure to run install.py in “configuration only” mode.
> 
> user@host:~/Malcolm$ ./scripts/install.py --configure
> 
> Alternately, if you are configuring Malcolm from the release tarball you will be asked if you would like to extract the contents of the tarball and to specify the installation directory and install.py will continue:

Then at the end of the that install script it [chowns](https://github.com/idaholab/Malcolm/blob/07389fb00e5699dbce2833b77eb559b816716443/scripts/install.py#L673-L681) the contents of the malcolm install directory to that of your user.

There's another question that's important, which is:

> Malcolm processes will run as UID 1000 and GID 1000. Is this OK? (Y/n): y

Those IDs should match those of your user (what you'd see running `id -u` and `id -g`).

So you are correct, the initial `install.py` should be run as root. If you need to reconfigure malcolm later (with `install.py --configure`), run `auth_setup` or any of the other scripts, you should run as the non-root user (which should be the same user ID / GID as the PUID and PGID values in the docker-compose file).

**Comment by carl-3** [comment]
Ok finally got docker issues taken care of, but now I'm running into a dashboard error with the same end-user problem (can't upload a file for analysis). 

![Screen Shot 2023-03-29 at 08 51 41](https://user-images.githubusercontent.com/113935499/228560168-0f18e4f9-2aa2-404d-8223-80fc192008e8.png)

**Comment by mmguero** [comment]
Looks like the opensearch container isn't running, which is almost 100% of the time due to resources issues. Malcolm (because of OpenSearch and Logstash) is a memory hog.

So let's check how much memory you've got total, and how much is allowed for OpenSearch and Logstash:

For example, on my workstation right now:

```
$ head -n 1 /proc/meminfo 
MemTotal:       65778428 kB

$ grep JAVA_OPTS docker-compose.yml
      OPENSEARCH_JAVA_OPTS : '-server -Xms30g -Xmx30g -Xss256k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true'
      LS_JAVA_OPTS : '-server -Xms6g -Xmx6g -Xss1536k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true'
```

So you can see my system has 64GiB of memory and I'm giving 30 of that to OpenSearch and 6 to LogStash.

Malcolm will run acceptably well for small analysis tasks on a system with 16GiB of memory (in which case, if I remember right, the `install.py --configure` script will suggest 10 for OpenSearch and 2.5 or so for Logstash). I have run it on systems with less than 16GiB (like 12 or maybe even 10) but it was pretty slow and I would occasionally get opensearch to crash on startup, similar to what you're seeing.

**Comment by mmguero** [comment]
That would be my guess. Even with OpenSearch set to 6G, there's probably some overhead in the container that takes it beyond the 7G you've set for it. you could run `docker-compose logs opensearch` after you've tried to start Malcolm up but opensearch is gone and you'll be able to see for sure.

**Comment by mmguero** [comment]
if you run `docker-compose logs opensearch` basically you'll see it start up and then shortly at the bottom of those logs you'll see a message about the container exiting.

I recommend a system with 16GB RAM and 4 CPU cores for Malcolm to run.

**Comment by carl-3** [comment]
Here's the last line:
![Screen Shot 2023-03-29 at 15 20 47](https://user-images.githubusercontent.com/113935499/228658091-cb262056-4287-475e-af58-fdb2c6eca557.png)

**Comment by mmguero** [comment]
definitely exiting prematurely. I can't say 100% if it's memory/resources related but I am pretty confident it is.

**Comment by carl-3** [comment]
But you think 16 GB would be enough? Or is that just speculation? I mean 64 GB is a good bit more than 16 GB.

**Comment by mmguero** [comment]
With OpenSearch/ElasticSearch the answer for memory is "the more the merrier." Ideally I think for doing serious volume analysis of network traffic 32GB+ is best, but I've found 16GB is usable. I've used 16GB laptops for Malcolm before or done it in VMs and that sort of thing. My best luck in an [AWS instance](https://aws.amazon.com/ec2/instance-types/) for bang-for-the-buck was the compute-optimized c4.4xlarge which is 30 GB and 16 cores.

**Comment by carl-3** [comment]
Ok, I've got 16 GB of RAM, removed the limits on logstash and opensearch, but am getting the same error

**Comment by mmguero** [comment]
I'm not sure what to tell you, I've seen a number of errors for different configuration reasons starting up Malcolm but never that one. I don't know wI guess my only suggestion would be to start fresh with an Ubuntu 22.04 or higher instance with the higher memory threshold and go through the [setup instructions](https://malcolm.fyi/docs/ubuntu-install-example.html#InstallationExample) again. Maybe there's some other issue with the underlying infrastructure I don't understand. I looked on the screenshot from your comments on the other thread and see you've got a reasonably up-to-date version of Docker. I also see you're running "Ubuntu Core 18," I'm not familiar with Ubuntu Core but from googling it tells me it's an all-snap based version of Ubuntu based on Ubuntu from April 2018 LTS. I'm grasping at straws though.

**Comment by carl-3** [comment]
Hmm, ok. From a more general side of things, could you tell me if Malcolm can extract specific data values from CIP packets?

**Comment by mmguero** [comment]
Here's the fields currently extracted from CIP, coming from our ethernet/ip parser:

* [fields captured](https://github.com/mmguero-dev/icsnpp-enip#logging-capabilities), see cip.log, cip_ip.log and cip_identity.log
* [example log files](https://github.com/mmguero-dev/icsnpp-enip/tree/main/tests/baseline/analyzer.basic)
* ethernet/ip dashboard:
![Dashboards - EtherNet_IP](https://user-images.githubusercontent.com/13872653/229858229-b0a297a2-0ef3-4349-b0b4-7f11811ef24d.png)

**Comment by mmguero** [comment]
I'm not the maintainer of that parser, I'm not intimately familiar with its internals. If you have a specific request or suggestion for that parser, I suggest you create an issue (with an attached sample PCAP file) to [icsnpp-enip](https://github.com/cisagov/icsnpp-enip).
