### ISSUE TITLE
opensearch container  fails 

### ISSUE THREAD

**Issue by vanyell** [idaholab/Malcolm#185]
using default docker-compose.yml

opensearch_1          | OpenSearch Performance Analyzer Plugin does not exist, disable by default
opensearch_1          | /usr/share/opensearch/opensearch-docker-entrypoint.sh: line 70:    52 Killed                  "$@" "${opensearch_opts[@]}"
opensearch_1          | usermod: no changes
opensearch_1          | opensearch
opensearch_1          | uid=1000(opensearch) gid=1000(opensearch) groups=1000(opensearch)
opensearch_1          |
opensearch_1          | OpenSearch Security Plugin does not exist, disable by default
opensearch_1          | OpenSearch Performance Analyzer Plugin does not exist, disable by default
opensearch_1          | usermod: no changes
opensearch_1          | opensearch
opensearch_1          | uid=1000(opensearch) gid=1000(opensearch) groups=1000(opensearch)
opensearch_1          |
opensearch_1          | OpenSearch Security Plugin does not exist, disable by default
opensearch_1          | OpenSearch Performance Analyzer Plugin does not exist, disable by default
opensearch_1          | /usr/share/opensearch/opensearch-docker-entrypoint.sh: line 70:    52 Killed                  "$@" "${opensearch_opts[@]}"

**Comment by mmguero** [comment]
Almost certainly an out-of-memory error. What's your total system memory and the opensearch_java_opts value? See https://malcolm.fyi/docs/malcolm-config.html#DockerComposeYml

**Comment by vanyell** [comment]
orgiinal system RAM 16G
OPENSEARCH_JAVA_OPTS : '-server -Xms10g -Xmx10g -Xss256k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true' (this was done by install.py --configure. Maybe need to adjust the computation? )

Taking into consideration of what you said .... increased RAM to 32 GB afterwards.. Worked
