### ISSUE TITLE
unexpected character "." in variable name

### ISSUE THREAD

**Issue by cyb3n3tic** [idaholab/Malcolm#217]
Apologies for this one, any pointers as to the cause of the error below when trying to start Malcom?

Malcolm failed to start

unexpected character "." in variable name near "logger.level=WARN\nbootstrap.memory_lock=true\nMAX_LOCKED_MEMORY=unlimited\ndiscovery.type=single-node\ncluster.routing.allocation.disk.threshold_enabled=false\ncluster.routing.allocation.node_initial_primaries_recoveries=8\nindices.query.bool.max_clause_count=4096\npath.repo=/opt/opensearch/backup\n"

**Comment by mmguero** [comment]
It seems like something's weird in your [config/opensearch.env](https://github.com/idaholab/Malcolm/blob/f76acfbcbe0a3b99c9ce033c088a649d0129cb7e/config/opensearch.env.example#L42-L49) file. Actually it seems like it's probably a line ending issue: can you check and see if `./config/opensearch.env` (and the other .env files in that directory) have weird line endings?

Like:

```
$ file config/opensearch.env
config/opensearch.env: ASCII text
```

**Comment by cyb3n3tic** [comment]
Thanks for the suggestion but all look ok. Odd one. I will keep poking it!

**Comment by mmguero** [comment]
What OS are you running this on? With the error message like that showing the `\n` in those lines from opensearch.env it really seems like something is expecting one type of line ending but getting another.

**Comment by cyb3n3tic** [comment]
It's on Ubuntu. It does read that way doesn't it

**Comment by cyb3n3tic** [comment]
Yep, think that is best. No special filesystem, problem came about through the upgrade process but I would say that was pilot error on my part rather than a Malcolm issue.
Thanks for your time, I'll go with a configure now and close this case.
Cheers

**Comment by cyb3n3tic** [comment]
Went for a rebuild in the end
