### ISSUE TITLE
Hedgehog 23.0.7.0 "Configure Interface and Hostname" not functioning

### ISSUE THREAD

**Issue by everettbukowski** [idaholab/Malcolm#227]
I just installed a fresh ISO of Hedgehog 23.0.7.0 and while trying to configure the network I click the "Configure Interface and Hostname" button, this brings up a prompt to enter the password. After entering the password it sits for a second or 2 before shutting the prompt down and nothing happens.

**Comment by mmguero** [comment]
The password you should use here is the root account password that's the very first password that you used when you were installing the ISO. The service account that runs all of the other processes on hedgehog does not have root privileges which are required for setting up the network interfaces.

**Comment by mmguero** [comment]
Any better luck with the root password?
