### ISSUE TITLE
add more vendors to NetBox manufacturers list

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#228]
We need to add more vendors to the list of NetBox manufacturers.

This will probably need to be done similar to how the [device roles](https://github.com/idaholab/Malcolm/blob/main/netbox/device-roles-defaults.json) are [imported on startup](https://github.com/idaholab/Malcolm/blob/1e748c84b6add6a2afe0ef0c9c232cb15edeba14/netbox/scripts/netbox_init.py#L413-L438).

If we end up adding actual device types, we should add them to [netbox-community/devicetype-library](https://github.com/netbox-community/devicetype-library) via pull request.

Minimally we should look at the [ICS vendors](https://github.com/idaholab/Malcolm/blob/main/logstash/maps/ics_macs.yaml). We should also just go through a big PCAP set and turn on NetBox auto populate and look for what shows up as "Unspecified."

**Comment by Crubumble** [comment]
Using the [String-Atlas](https://github.com/DINA-community/String-Atlas) on CSAF documents up to december 2024. The list of manufacturers (vendors) was created under the [dev branch](https://github.com/DINA-community/String-Sysiphos/tree/dev). Not every manufacturer should be considered. Therefore, the entries for `manufacturer.yaml` contain a group field as well as a info field about the company. 

The field `group` divided the companies into different working areas:

- Group1: Core industrial hardware/components (e.g. B&R, Beckhoff).
- Group2: Industrial hardware with slight uncertainty or overlap to other group, also default input of Malcolm
- Group3: IT-hardware products (networking, surveillance, radio).
- Group4: Safety related but not directly in industrial environment (locks, alarm, webcam, acoustic)
- Group5: Medical hardware
- Group6: Pure software or CAD/engineering tools.
- Group7: Group for remaining companies

Group6 could be divided further into OT focused and non OT focused software and tools. Nevertheless, the existing group field structure allows to filter the list when generating a yaml for NetBox.
