### ISSUE TITLE
Malcolm server's nic does not connect after booting when using dhcp

### ISSUE THREAD

**Issue by patrickpritchett** [idaholab/Malcolm#241]
It will connect when you click network connections then click Wired Connection 1. The Hedgehog server connects fine.
Servers installed using the ISO's for Malcolm and Hedgehog from https://malcolm.fyi/docs/download.html

I created file `/etc/network/interfaces.d/enp39s0` , added info below and it came up fine after reboot
```
auto enp39s0 
iface enp39s0 inet dhcp
```
However a different interface still tries and fails to DHCP every 5 minutes even though there is only one interface physically connected.

**Comment by mmguero** [comment]
The Malcolm desktop environment uses [Network Manager](https://wiki.debian.org/NetworkManager) pretty vanilla, we're not really customizing that aspect of the installed environment at all. I can try to duplicate your experience with a VM, in all of my hardware and virtualized installations I'm not having the problem you're describing.

So you've got multiple physical interfaces, but the wrong one (one that doesn't have a link connected) is the one it's trying to DHCP on? Could you right-click on the network manager icon in the tray, select "Edit Connections", delete the connection it's trying to use and create a new one which is using DHCP for the right interface?

**Comment by patrickpritchett** [comment]
I will reinstall the Malcolm node and validate the issue persists
