### ISSUE TITLE
Opensearch health check never passes on ubuntu install

### ISSUE THREAD

**Issue by patrickpritchett** [idaholab/Malcolm#242]
Using instructions from https://malcolm.fyi/docs/ubuntu-install-example.html#InstallationExample with git clone. 

Adding **opensearch** to the loopback line in `/etc/hosts` stopped the second error below but nothing(arkime, dashboards) works as expected.
1.
```
malcolm-pcap-monitor-1        | 2023-08-16 14:19:40 WARNING: GET http://opensearch:9200/_cluster/health [status:N/A request:0.374s]
malcolm-pcap-monitor-1        | ConnectionRefusedError: [Errno 111] Connection refused
malcolm-pcap-monitor-1        |
malcolm-pcap-monitor-1        | During handling of the above exception, another exception occurred:
malcolm-pcap-monitor-1        |
malcolm-pcap-monitor-1        | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa7c2dcf040>: Failed to establish a new connection: [Errno 111] Connection refused
```
2.
```
malcolm-pcap-monitor-1        | 2023-08-16 14:48:16 WARNING: GET http://opensearch:9200/_cluster/health [status:N/A request:0.133s]
malcolm-pcap-monitor-1        | socket.gaierror: [Errno -2] Name or service not known
malcolm-pcap-monitor-1        |
malcolm-pcap-monitor-1        | During handling of the above exception, another exception occurred:
malcolm-pcap-monitor-1        |
malcolm-pcap-monitor-1        | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa7c2df0c70>: Failed to establish a new connection: [Errno -2] Name or service not known
```

**Comment by mmguero** [comment]
You shouldn't have to modify `/etc/hosts` on your host machine at all. I strongly suspeect opensearch is failing to start completely because of resource (memory) constraints. How much memory is physically present on this system, and how much have you given to OpenSearch and Logstash, e.g.,

```
config/logstash.env:LS_JAVA_OPTS=-server -Xms3g -Xmx3g -Xss1536k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true
config/opensearch.env:OPENSEARCH_JAVA_OPTS=-server -Xms24g -Xmx24g -Xss256k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true
```

**Comment by patrickpritchett** [comment]
It is running on a Virtualbox vm(4g mem) from an old Lenovo laptop running Ubuntu 20.04. That may be an issue. I am mostly using defaults during install.py, configure and auth_setup. I add Netbox and NB discovery, which works on the other system.

I am testing some things locally in VMs and others on actual Malcolm/Hedgehog server pair with good hardware.

**Comment by mmguero** [comment]
Minimum recommended memory for Malcolm is 16GB. A *bare* minimum would be maybe 12GB. That's definitely the problem in this case.
