### ISSUE TITLE
Hedgehog - beats:miscbeat service crashes

### ISSUE THREAD

**Issue by patrickpritchett** [idaholab/Malcolm#244]
Servers installed using the ISO's for Malcolm and Hedgehog from https://malcolm.fyi/docs/download.html

`sensor@hedgehog:sensor_ctl# ./status`
```
beats:miscbeat                   FATAL     Exited too quickly (process log may have details)
```
`sensor@hedgehog:sensor_ctl$ tail log/miscbeat-stderr---supervisor-v2qt6sr_.log`
```
{"log.level":"error","@timestamp":"2023-12-16T13:50:39.263Z","log.origin":{"file.name":"instance/beat.go","file.line":1274},"message":"Exiting: error initializing publisher: could not setup output certificates reloader: unpacking 'ssl' config: missing field accessing 'output.logstash.ssl.verification_mode' (source:'/opt/sensor/sensor_ctl/miscbeat/filebeat.yml')","service.name":"filebeat","ecs.version":"1.6.0"}
Exiting: error initializing publisher: could not setup output certificates reloader: unpacking 'ssl' config: missing field accessing 'output.logstash.ssl.verification_mode' (source:'/opt/sensor/sensor_ctl/miscbeat/filebeat.yml')
```

**Comment by mmguero** [comment]
Have you [transferred the certificate files](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#HedgehogGetCerts) from Malcolm to Hedgehog so that they're in `/opt/sensor/sensor_ctl/logstas-client-certificates` (or elsewhere if you specified a custom location?

**Comment by mmguero** [comment]
And have you gone through the [rest of the capture/forward configuration](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#HedgehogCapture)? That service is working fine for me.

**Comment by patrickpritchett** [comment]
Yes. Transferring certs was required to get Hedgehog to communicate back to Malcolm. I will test more and report back

**Comment by mmguero** [comment]
Thanks, I've never seen that error (about `output.logstash.ssl.verification_mode` missing) before. My best guess here is that you set the autostart to true for some of these "miscbeat" services (forwarding system metrics of the sensor itself to Malcolm) but didn't actually complete the `miscbeat` section of the forwarding configuration.

**Comment by patrickpritchett** [comment]
I re ran configure-capture and reconfigured miscbeat. It is now working fine. Guess it was a mis-configuration.
