### ISSUE TITLE
NetFlow v9 input

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#248]
A user requested we look into accepting NetFlow v9 as a flow data source. I believe there are netflow inputs for logstash and filebeat already, so the plumbing is there. The majority of the work would be in normalizing the flow data to match, but there's a good chance that it's already going to be targeting ECS anyway.

**Comment by StammesOpfer** [comment]
Maybe some collab?
https://github.com/arkime/arkime/issues/1617

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/467)
