### ISSUE TITLE
Croc dependency not included or discussed in ubuntu install example

### ISSUE THREAD

**Issue by 0xshaft03** [idaholab/Malcolm#271]
As it stands, on a default install of ubuntu 22.04, the installation comes to a halt when setting up Hedgehogs due to the lack of "croc".

`./scripts/control.py`
```
 line 1088: if (pyPlatform != PLATFORM_WINDOWS) and which("croc"):
```
This results in the `txfwcerts` not being presented in the `auth_setup` menu.

Installing croc from `https://github.com/schollz/croc` resolves this issue.

**Comment by mmguero** [comment]
Thanks! The croc bit was added mainly as convenience for the ISO-installed Malcolm system (where I have control over what's in the image and am including croc by default there), but it does make sense to document it for the straight docker installation too. I may change the wording just a bit as it is not a hard requirement (you can still copy the certs over manually) but rather a convenience. I'll pull your PR into my development fork and alter it slightly.

**Comment by mmguero** [comment]
I've pulled in your commit (see mmguero-dev/Malcolm@5eb8d8997076bb2eefc5b2f74e92a7988b0078ef) and made a slight adjustment to the wording (see mmguero-dev/Malcolm@b867b326ef1689f08f8c7992cb6d0685829168b8) into my development fork. This change will get included in the next release. Thanks!
