### ISSUE TITLE
integrate nsacyber/ELITEWOLF signatures into default rule set

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#275]
NSA cyber's [ELITEWOLF](https://github.com/nsacyber/ELITEWOLF) project releases some OT-focused Snort rules. I'd like to:

* review these rules
* convert from Snort to Suricata (see https://docs.suricata.io/en/latest/rules/differences-from-snort.html)
* test them
* include them as part of Malcolm's default rule set

**Comment by IdahoManny** [comment]
### Converted and Tested Snort to Suricata
Suricata does have compatibility with snort rules. The files below were taken from the repository and tested with Suricata. Change file names from `.txt` to `.rules` file and place in `/etc/suricata/rules/path`. Sample log file is also attached. Test of rules were conducted with netcat.  

[Tested-ELITEWOLF_SNORT_AllenBradley_RockwellAutomation.txt](https://github.com/idaholab/Malcolm/files/13323199/Tested-ELITEWOLF_SNORT_AllenBradley_RockwellAutomation.txt)
[Tested-ELITEWOLF_SNORT_SchweitzerEngineeringLaboratories.txt](https://github.com/idaholab/Malcolm/files/13323200/Tested-ELITEWOLF_SNORT_SchweitzerEngineeringLaboratories.txt)
[Tested-ELITEWOLF_SNORT_Siemens.txt](https://github.com/idaholab/Malcolm/files/13323201/Tested-ELITEWOLF_SNORT_Siemens.txt)
[logs.txt](https://github.com/idaholab/Malcolm/files/13323202/logs.txt)
