### ISSUE TITLE
Add Custom Suricata rules 

### ISSUE THREAD

**Issue by jo-zef** [idaholab/Malcolm#305]
new custom Suricata rules were being pulled from /Malcolm/suricata/rules to Suricata docker but it is not active, no alerts for the new custom rules

Is there any extra configuration to enable ?

PS:  "SURICATA_CUSTOM_RULES_ONLY=" is True under  Malcolm/config/suricata.env

**Comment by mmguero** [comment]
Seems to be working fine for me. Here's what I did with a clean installation of Malcolm:

1. I created a file with a `.rules` extension in ./suricata/rules under Malcolm that contains a Suricata rule
    * I used [this rule for testing](https://docs.suricata.io/en/suricata-6.0.9/quickstart.html#alerting)
2. I don't know if you're doing [live analysis](https://idaholab.github.io/Malcolm/docs/live-analysis.html#LiveAnalysis) or [pcap upload](https://idaholab.github.io/Malcolm/docs/upload.html#Upload) but make sure you have that configured and working first (i.e., you're getting other logs in the dashboards, right?). If you're not getting any logs at all, then Suricata is not the problem, you just need to go through the setup more carefully, see [this example](https://idaholab.github.io/Malcolm/docs/ubuntu-install-example.html#InstallationExample) and [this example](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#MalcolmConfig).
3. my `SURICATA_CUSTOM_RULES_ONLY=true` is set in my suricata.env
4. I started Malcolm
5. Let Malcolm start up (i.e., give it a few minutes for the `./scripts/start` script to return)
6. I browsed to a web site that triggered my test rule [http://testmynids.org/uid/index.html](http://testmynids.org/uid/index.html)
7. After a few minutes I browsed to Malcolm's Dashboards and went to the Suricata dashboard, here's from the bottom of that:

![image](https://github.com/idaholab/Malcolm/assets/13872653/f3503ad1-5017-40ae-b0a7-a3eac01dbbae)

You can also run `./scripts/logs -s suricata-live`(if you're doing live capture) and you'll see the output logs from the Suricata container:

```
...
malcolm-suricata-live-1  | 6/12/2023 -- 15:03:56 - <Info> - 1 rule files processed. 1 rules successfully loaded, 0 rules failed
malcolm-suricata-live-1  | 6/12/2023 -- 15:03:56 - <Info> - Threshold config parsed: 0 rule(s) found
malcolm-suricata-live-1  | 6/12/2023 -- 15:03:56 - <Info> - 1 signatures processed. 0 are IP-only rules, 1 are inspecting packet payload, 0 inspect application layer, 0 are decoder event only
...
```

As you can see, in this case only my one custom rule is getting loaded.
