### ISSUE TITLE
Users tab is empty

### ISSUE THREAD

**Issue by vanyell** [idaholab/Malcolm#320]
Using both prebuilt docker  images and building from source. Users tab remains empty. Did I miss anything perhaps?

![image](https://github.com/idaholab/Malcolm/assets/863311/904acfd2-b017-4842-a8e0-11c091d99d8e)

**Comment by mmguero** [comment]
Malcolm doesn't use Arkime's user management interface. [User accounts can be created](https://idaholab.github.io/Malcolm/docs/authsetup.html#AuthBasicAccountManagement) at https://#.#.#.#/auth
