### ISSUE TITLE
add option for netbox_init to wait for postgres connection before preloading items

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#326]
A request was made to provide an option for the netbox_init.py script to wait (probably wait for up to a certain amount of time?) for a good postgresql connection before preloading its items. The user's scenario is a custom postgresql DB backend.

**Comment by pleasantencounter** [comment]
@mmguero I agree with a certain wait period.  Setting an env variable to override the time would be ideal, but we can default it to 1 or 2 mins.

**Comment by mmguero** [comment]
I'm going to wait for the v24.01.0 release before moving on this, as I [redid the preload code](https://github.com/mmguero-dev/Malcolm/compare/9486b3a72f49781ea211e1b5b73e7e3f1724aa4f...c6298b583de4d55ea94f556615f687cb70b423ad) and want to see if the underlying issue is fixed.
