### ISSUE TITLE
no way to logout of Malcolm

### ISSUE THREAD

**Issue by ericnnn123** [idaholab/Malcolm#405]
Include some way to log out of Malcolm on the dashboard or the user management.

**Comment by piercema** [comment]
Malcolm uses HTTP Basic-Authentication with an nginx proxy. Per the nginx documentation [here](https://docs.nginx.com/nginx-management-suite/admin-guides/authentication/basic-authentication/) there is no "Log Out" button. To log out of Malcolm, yyou can either close your browser or edit your active sessions in the browser settings.

**Comment by mmguero** [comment]
Something that might help us in the future. Not exactly the same thing, but does provide digest-based auth with a session timeout (which could maybe be used to force a "log out"): https://github.com/samizdatco/nginx-http-auth-digest

**Comment by mmguero** [comment]
See also: [Mozilla Firefox Issue Tracker: Usability: Allow users to clear HTTP Basic authentication details ('Logout')](https://bugzilla.mozilla.org/show_bug.cgi?id=540516)

**Comment by mmguero** [comment]
not planned

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/408)
