### ISSUE TITLE
After fresh install arkime and Open Search does not work

### ISSUE THREAD

**Issue by TollerEmil** [idaholab/Malcolm#408]
**Describe the bug**
After a Clean setup on Ubuntu 22.04 Arkime, Cyberchef shows the following error " {"success":false, "text":"User not found"} ". Dashboards has no Dashboards.

**Screenshots and/or Logs **
During the startup the log shows: [error][date][opensearch] [ConnectionError]: getaddrinfo ENOTFOUND opensearch

**Malcolm Version:**
 - Version v24.01.0

**How are you running Malcolm?**
Git clone on a fresh installed Ubuntu 22.04

**Comment by mmguero** [comment]
Usually when services don't start up or aren't reachable it has to do with the resources available to the containers.

If you run `./scripts/status` from the Malcolm directory, what do you see? Are any of the containers showing as exited or not healthy in the `STATUS` column?

What are the resources (specifically available RAM) of the host? And how much memory allocated for Logstash and OpenSearch (`grep -Po "\w+_JAVA_OPTS.+Xm[sx]\w+" config/*.env` will give you those figures)? Usually containers failing to stay started are dealing with limited resources.

Beyond that, maybe you can get it started up and into this state and then run `docker compose --profile malcolm logs > output.txt` (or `docker-compose` if `docker compose` returns an error) and attach the contents of that file to this issue and I can try to make a better guess.

**Comment by mmguero** [comment]
Any update on this, @TollerEmil ?

**Comment by TollerEmil** [comment]
Okay, now it is running. It was a Performance issue. So i changed the hardware and now everything is fine.
