### ISSUE TITLE
integrate JA4 zeek plugin

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#419]
integrate JA4.

Not sure if [this repo](https://github.com/anthonykasza/ja4) or [this repo](https://github.com/FoxIO-LLC/ja4/tree/main/zeek) is the one we should use?

**Comment by mmguero** [comment]
Also, is this supplementing or replacing JA3?

**Comment by piercema** [comment]
This will replace JA3. 
"JA4+ provides a suite of modular network fingerprints that are easy to use and easy to share, replacing the JA3 TLS fingerprinting standard from 2017. These methods are both human and machine readable to facilitate more effective threat-hunting and analysis." [Source](https://blog.foxio.io/ja4%2B-network-fingerprinting).

The [FoxIO repo](https://github.com/FoxIO-LLC/ja4/tree/main/zeek) is company maintained. We will use this version of the package.

**Comment by mmguero** [comment]
Good blog post:

https://blog.foxio.io/ja4%2B-network-fingerprinting

**Comment by mmguero** [comment]
Arkime JA4 fields (will be in v24.04.0 of Malcolm):

![image](https://github.com/idaholab/Malcolm/assets/13872653/db8d8254-7a95-409a-9885-1fb6e5d27bd8)

**Comment by piercema** [comment]
We are waiting for Suricata to also upgrade to JA4. The following approved PR[https://github.com/OISF/suricata/pull/10725] will implement JA4 and should be released relatively soon. We are pushing the release of this until Suricata is also updated.

**Comment by piercema** [comment]
It appears that version 8.0 of Suricata will contain the JA4 updates. See https://github.com/OISF/suricata/pull/10856

**Comment by mmguero** [comment]
Did a quick and dirty test to look at the field values being generated like this:

```bash
for FIELD in $(dc exec api curl -sSL localhost:5000/mapi/fields | jq | grep ja4 | awk '{print $1}' | sed 's/"//g' | cut -d: -f1 | grep -v Cnt); do \
  dc exec api curl -sSL "localhost:5000/mapi/agg/event.provider,$FIELD?from=1970" | jq > /tmp/"$FIELD".json; \
done
```

Then examine the .json files in /tmp/
