### ISSUE TITLE
htadmin creating entries without a newline between them in the htpasswd file

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#426]
A partner found a scenario in which using [local account management](https://idaholab.github.io/Malcolm/docs/authsetup.html#AuthBasicAccountManagement) adding a new user would cause the user's information to be added to the end of the htpasswd file without a newline. This would result in neither the original or the new user could log in.

Need to investigate to reproduce and see what's happening there. I'd be interested to know if:

* the original entry in htpasswd ended in a newline or not?
* what happens if we add a third user at the same time as we add the second one? is it also just on the same line?

**Comment by supcom234** [comment]
Steps to reproduce:
1. Create a fresh cluster uisng vagrant up within the Malcolm-Helm project.
2. Login to admin panel
3. Add a username with a period in it (IE: david.navarro)
4. Create a 8 character password

Expected Result
Should have a new line character between the user entries

Actual result 
Users get created on same line in htpasswd file.

**Comment by mmguero** [comment]
It looks like to me that this happens when the initial htpasswd does not contain a trailing newline.

**Comment by mmguero** [comment]
[Fixed upstream in htadmin](https://github.com/mmguero-dev/htadmin/compare/1665d6c8392d43c38b21698b75826234098f34b3...d84ac882fc255df3093e46217bcf4e977f9ba716)

**Comment by mmguero** [comment]
Apparently this is still an issue: somehow on an environment I'm testing on I the newline got added, but it also stripped the last character from the line. I need to see what happened, and why it worked in my test but not on this system in the environment

**Comment by mmguero** [comment]
[These two commits](https://github.com/mmguero-dev/htadmin/compare/d84ac882fc255df3093e46217bcf4e977f9ba716...ff7ccaa9e759b8844637fbfb681ed1b8c7cde411) ([wrapped in to the original commits](https://github.com/mmguero-dev/htadmin/compare/1665d6c8392d43c38b21698b75826234098f34b3...ff7ccaa9e759b8844637fbfb681ed1b8c7cde411)) now have resolved the issue. I've tested it:

* with Malcolm in a docker-based installation, with htpasswd files with and without the \n
* with Malcolm in a Kubernetes-based installation, with htpasswd bootstrapped via configmap from an existing file on the machine with and without the \n
* on our partner's site, with htpasswd bootstrapped via configmap from a string with and without the \n

In all cases I was able to log in, log into the user management interface, create and delete accounts, and log in with those accounts.
