### ISSUE TITLE
Integrate Scirius CE for Suricata

### ISSUE THREAD

**Issue by ArmsSec** [idaholab/Malcolm#430]
I think it might can be useful to integrate Scirius CE for Suricata ruleset management. It is a web GUI that can help in managing the Suricata rules.
Scirius CE is developed by [Stamus Networks](https://www.stamus-networks.com/) and is available under the GNU GPLv3 license.

**Comment by mmguero** [comment]
Thanks for the suggestion!

**Comment by PrplHaz4** [comment]
https://github.com/StamusNetworks/scirius for anyone interested in learning more

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/402)
