### ISSUE TITLE
Exception: auth_setup should not be run as root

### ISSUE THREAD

**Issue by kirankalelkar** [idaholab/Malcolm#443]
i have tried but no luck when i run the ./scripts/auth_setup getting below error.
Exception: auth_setup should not be run as root

please check below screenshot for your referance.
![malcolm fail 1](https://github.com/idaholab/Malcolm/assets/163304329/428c69f4-be20-4127-bd4f-c3408dab8f5e)

**Comment by mmguero** [comment]
Looking at the screenshot, very first line, I can see "root@". For security reasons, Malcolm should not be installed nor run as the root user, just as that error message says. You should start your installation over and make sure that the Malcolm installation directory is owned by a non-root user, and that you run configure and auth_setup as a non-root user.

**Comment by kirankalelkar** [comment]
i tried with non-root user but getting same issue. Please check attached screenshot for your referance.

![malcolm fail 2](https://github.com/idaholab/Malcolm/assets/163304329/54c10afd-7107-453f-87c7-496eb7d58499)

**Comment by mmguero** [comment]
I apologize for the confusion. In that screenshot you're running `install.py`, which does prompt you to make some system changes (e.g., changes to sysctl.conf) which does require root. However, once the `install.py` stage is done, the `configure` and `auth_setup` steps are done as non-root.

That is what is outlined in [the documentation](https://idaholab.github.io/Malcolm/docs/ubuntu-install-example.html#InstallationExample).

**Comment by kirankalelkar** [comment]
Sir i tried the same install.py run from root user and configure and auth_setup run using non root user but getting same issue.
please check last comment screenshot and check the below mentioned error.

test@malcolm-test:/opt/Malcolm$ **./scripts/auth_setup
Exception: auth_setup requires docker, please run install.py**
