### ISSUE TITLE
Configuring Hedgehog Linux

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#451]
**For what topic would you like to see training developed?**
Configuring Hedgehog Linux after the ISO installation

**What format would be best suited for this training?**
A brief video

**Is there existing [Malcolm documentation](https://idaholab.github.io/Malcolm/) that could be improved by including this topic?**
Yes, starting [here](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#HedgehogInterfaces).

**Comment by Zokol** [comment]
While trying to debug https://github.com/idaholab/Malcolm/issues/490 I needed to access the process logs in Hedgehog. It might be good idea to highlight that all relevant logs in Hedgehog can be found from `/opt/sensor/sensor_ctl/logs`

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/398)
