### ISSUE TITLE
Cannot complete build.sh

### ISSUE THREAD

**Issue by vanyell** [idaholab/Malcolm#481]
**Describe the bug**
Running scripts/build.sh
error with  ghcr.io/idaholab/malcolm/file-upload:24.04.0

1738.1 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
1739.8 curl: (22) The requested URL returned error: 404

**To Reproduce**
Run scripts/build.sh
**Expected behavior**
Build all images successfully

**Screenshots and/or Logs **
![Screenshot 2024-05-27 185726](https://github.com/idaholab/Malcolm/assets/863311/bf3fdf6a-986b-45e9-8cb5-4b4aac1a34ca)

**Malcolm Version:**
v24.04

**How are you running Malcolm?**
via Docker ..

**Comment by mmguero** [comment]
Zeek has updated to a new version and as such has removed the old URLs from the location referenced by the Docker image. The next release of Malcolm (to be released this week) will point at the updated Zeek .debs.
