### ISSUE TITLE
Arkime viewer not rolling pcaps

### ISSUE THREAD

**Issue by coffeecoffeecoffeecoffeecoffee** [idaholab/Malcolm#484]
**Describe the bug**

We are running a full Malcolm setup with docker compose using the `malcolm` profile that monitors a local network interface with `netsniff-ng`. As per the docs for a low resources environment, `SURICATA_LIVE_CAPTURE` / `ZEEK_LIVE_CAPTURE` are set to `false` and `SURICATA_ROTATED_PCAP` / `ZEEK_ROTATED_PCAP` are set to `true`. 

Pcaps are filling up the drive they are on, even with `MANAGE_PCAP_FILES` set to `True`. Everything  shows `False` under `Locked` in the arkime `files` tab. 

**Expected behavior**

The  `arkime` container should delete pcaps once the disk usage has surpassed the designated amount of free space.

**Malcolm Version:**
 - v24.04.0

**How are you running Malcolm?**
- [ ] [ISO installed](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) (on VM or dedicated hardware)
- [x] via [Docker](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) on [Linux](https://idaholab.github.io/Malcolm/docs/host-config-linux.html#HostSystemConfigLinux)
- [ ] via Docker on [Microsoft Windows](https://idaholab.github.io/Malcolm/docs/host-config-windows.html#HostSystemConfigWindows)
- [ ] via Docker on [macOS](https://idaholab.github.io/Malcolm/docs/host-config-macos.html#HostSystemConfigMac)
- [ ] via [Kubernetes](https://idaholab.github.io/Malcolm/docs/kubernetes.html#Kubernetes) (please provide platform details: e.g., on-prem K3s, Amazon AWS EKS, Microsoft Azure AKS, etc.)
- [ ] other (please describe)

**Additional context**

Upon further investigation, I found an old [issue](https://github.com/cisagov/Malcolm/issues/114) and this [commit](https://github.com/cisagov/Malcolm/commit/b4b6586982a67ffa3b473462bbc2200e5222e667) that referenced the same problem. In the `arkime` container, the `pcapDir` was set to `/data/pcap/arkime-live` by the docker entrypoint. After changing the `pcapDir` back to `processed` in the `config.ini` and restarting the viewer process, it correctly removed pcaps to make space.

I'm assuming the issue lies [here](https://github.com/cisagov/Malcolm/blob/84679301b20aedca1b9548916de891144ca10545/arkime/scripts/docker_entrypoint.sh#L70), but I'm not very familiar with Malcolm. We are not using arkime live capture so I wonder if that replacement should only be applied when that is the case?

**Comment by mmguero** [comment]
I thought that the line you referenced in your last comment actually doesn't make any difference when `arkime-live` isn't doing the capture (which it isn't in your case). It should just be [these two variables](https://github.com/idaholab/Malcolm/blob/ea78671563f6cf444dac08d0c689e96a5bc6d0ed/config/arkime.env.example#L4-L5) that come into play. But I'll look closer at it tomorrow and see if I can reproduce the issue; it may be that viewer is basing what it does on that directory you linked for its free space calculations, in which case it should be an easy fix. Thanks for bringing it to my attention.

**Comment by mmguero** [comment]
Thanks, you're exactly right. I've adjusted the entrypoint to only change that location in the case where it's actually doing live capture.
