### ISSUE TITLE
Hedgedog-raspi make fails

### ISSUE THREAD

**Issue by Zokol** [idaholab/Malcolm#486]
**Describe the bug**
When following the instructions in [hedgehog-raspi/README.md](https://github.com/idaholab/Malcolm/blob/main/hedgehog-raspi/README.md), the `make raspi_4_bookworm.img` fails with `EBUG STDERR: cp: cannot stat '/home/red/Malcolm/hedgehog-iso/arkime/etc/*': No such file or directory`

**To Reproduce**
1. Follow instructions: 
```
git clone https://github.com/idaholab/Malcolm.git
cd Malcolm/hedgehog-raspi
apt install -y vmdb2 dosfstools qemu-utils qemu-user-static debootstrap binfmt-support time kpartx bmap-tools python3 zerofree
apt install -y fakemachine
make raspi_4_bookworm.img
```
2. See error in `raspi_4_bookworm.log`

**Expected behavior**
Expected to create `raspi_4_bookworm.img`

**Malcolm Version:**
 - Commit ea78671563f6cf444dac08d0c689e96a5bc6d0ed

**Log**
[raspi_4_bookworm.txt](https://github.com/user-attachments/files/15721692/raspi_4_bookworm.txt)

**Comment by mmguero** [comment]
The way I build the official raspi images is using the [`./hedgehog-raspi/build_via_vagrant.sh`](https://github.com/idaholab/Malcolm/blob/main/hedgehog-raspi/build_via_vagrant.sh) which in turn run `make` inside [a virtual machine](https://github.com/idaholab/Malcolm/blob/main/hedgehog-raspi/vagrant/Vagrantfile). I'd recommend looking at those scripts to see how it's doing it, or using that script directly.
