### ISSUE TITLE
No option to go backwards in Malcolm install tool

### ISSUE THREAD

**Issue by Zokol** [idaholab/Malcolm#487]
**Describe the bug**
While installing Malcolm from ISO, the installation tool automatically opens.
If user select incorrect value and selects "ok", the tool does not allow reversing the selection. With multiple steps in installation process, it is likely that at some point user sets incorrect value by accident.

**To Reproduce**
1. Start install process using Malcolm ISO
2. Press `yes` on first installation step
3. There is now no way to go back and select `no` for the first step without restarting the installation process

**Expected behavior**
Add `back`-button to every step to allow user to go back to previous steps

**Screenshots and/or Logs **

**Malcolm Version:**
 - Version [e.g. v24.05.0]

**How are you running Malcolm?**
- [ISO installed](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) (VM)

**Comment by mmguero** [comment]
![Image](https://github.com/user-attachments/assets/bf6d310b-a537-4c17-8f80-db6afc218bc5)



![Image](https://github.com/user-attachments/assets/5e27ed37-4ae9-4e25-a4b8-093e5d7efe18)



![Image](https://github.com/user-attachments/assets/dad72f9e-2529-4707-82e2-45cb0af06f1c)



![Image](https://github.com/user-attachments/assets/64931925-45df-4d89-8544-bd297cbdd82d)

**Comment by mmguero** [comment]
the code isn't too honky to handle the back stuff:

* [define a list of operations](https://github.com/mmguero-dev/Malcolm/blob/6aa93785da3d2fc80d0a6b04596e3abedebf76a5/scripts/install.py#L130-L156)
* [loop forever](https://github.com/mmguero-dev/Malcolm/blob/6aa93785da3d2fc80d0a6b04596e3abedebf76a5/scripts/install.py#L622-L627)
* [set the appropriate previous operation if back was selected](https://github.com/mmguero-dev/Malcolm/blob/6aa93785da3d2fc80d0a6b04596e3abedebf76a5/scripts/install.py#L1941-L1948)
* [break when done with the final one](https://github.com/mmguero-dev/Malcolm/blob/6aa93785da3d2fc80d0a6b04596e3abedebf76a5/scripts/install.py#L1938-L1939)

Note that is only going to be in the "dialog" version of the script (not the plain version) and only for the `-c`,`--configure` part of the script, but I think that's the one that people care about most for this. The "install" part of the script that actually changes system files needs to go through end-to-end like before, but you do that a lot less frequently.
