### ISSUE TITLE
OpenSearch to Splunk export/searching capabilities

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#5]
From Malcolm created by [mmguero](https://github.com/mmguero): cisagov/Malcolm#10  

Research ES to Splunk export/searching capabilities

Possibilities:

- Forwarding from ES via Logstash syslog
    - https://www.elastic.co/guide/en/logstash/current/plugins-inputs-elasticsearch.html
    - https://www.elastic.co/guide/en/logstash/current/plugins-outputs-syslog.html
- Searching ES databases with Splunk
    - https://github.com/brunotm/elasticsplunk
    - https://splunkbase.splunk.com/app/4175/#/details
  - https://github.com/hvandenb/splunk-elasticsearch

**Comment by nilssachs** [comment]
Would be a great addition. Currently struggling with the Syslog-output.

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/487)
