### ISSUE TITLE
Not bug, missing documentation

### ISSUE THREAD

**Issue by y0d4a** [idaholab/Malcolm#502]
Hi, i cannot find in documentation how to add ETPRO ruleset for zeek (dockerized) ?

tnx.

**Comment by mmguero** [comment]
Documentation for loading custom Zeek scripts is [here](https://idaholab.github.io/Malcolm/docs/custom-rules.html#Zeek). Drop the custom script(s) into the `./zeek/custom/ `, for which you'd also need to create a `__load__.zeek` file to tell zeek how to load that directory.
