### ISSUE TITLE
air gapped environment

### ISSUE THREAD

**Issue by devilman85** [idaholab/Malcolm#503]
How can I install Malcolm in an air gapped environment and have zeek, meerkat, calmv and yara signatures updated?

**Comment by mmguero** [comment]
In an air-gapped environment the only way to currently get signatures updated is through [upgrading Malcolm](https://idaholab.github.io/Malcolm/docs/malcolm-upgrade.html#UpgradePlan), for which there is not a terrific procedure yet. Mainly, though, it would involve getting the latest Malcolm docker images and loading them, in addition to updating any new related configuration (.env files, the docker-compose files, etc.).
