### ISSUE TITLE
Can't connect to Docker daemon, Alma Linux.

### ISSUE THREAD

**Issue by njohnson256** [idaholab/Malcolm#511]
**Describe the bug**
Unable to start Malcolm due to docker error. After running the start script you receive an error that you can't connect to the Docker daemon. You can run docker info but the docker group wasn't created during the Docker install. 

**To Reproduce**
1. Install Malcolm with git clone https://githib.com/idaholab/Malcolm
2. Run sudo ./scripts/install.py and complete install.
3. Reboot system
4. Run ./scripts/auth_setup and set up administrator account. 
5. Run ./scripts/start
6. See error

**Expected behavior**
Expected to be able to start Malcolm in browser with link given by the start script.

**Screenshots and/or Logs **
If applicable, attach screenshots or container logs (e.g., the relevant bits of `./scripts/logs`) to help explain your problem.

![Screenshot from 2024-07-01 10-46-46](https://github.com/idaholab/Malcolm/assets/174061044/d98fd46a-bbc0-4bed-9f86-2979e3be1b31)

**Malcolm Version:**
 - Version v24.06.0

**How are you running Malcolm?**
- [x] [ISO installed](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) (on VM or dedicated hardware)
- [ ] via [Docker](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) on [Linux](https://idaholab.github.io/Malcolm/docs/host-config-linux.html#HostSystemConfigLinux)
- [ ] via Docker on [Microsoft Windows](https://idaholab.github.io/Malcolm/docs/host-config-windows.html#HostSystemConfigWindows)
- [ ] via Docker on [macOS](https://idaholab.github.io/Malcolm/docs/host-config-macos.html#HostSystemConfigMac)
- [ ] via [Kubernetes](https://idaholab.github.io/Malcolm/docs/kubernetes.html#Kubernetes) (please provide platform details: e.g., on-prem K3s, Amazon AWS EKS, Microsoft Azure AKS, etc.)
- [ ] other (please describe)

**Additional context**
According to the docker website Alma isn't supported by docker but other sources say it's still possible to use docker with Alma.

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/385)
