### ISSUE TITLE
transition from ElasticSearch to OpenSearch

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#54]
This issue is for tracking the transition from ElasticSearch to the open source fork, OpenSearch.

Malcolm will be switching to the [OpenSearch](https://opensearch.org/) project as the basis of its search and analytics capabilities, mainly for two reasons:

1. Elastic.co's decision to no longer release Elasticsearch and Kibana under an open source license
2. Capabilities available under OpenSearch (and previously under Open Distro for Elasticsearch) that are only available with paid "premium" Elastic.co subscriptions (machine learning anomaly detection, alerting, reporting, etc.)

**Historical context:**

* Elastic announces license change
  * [Amazon NOT OK](https://www.elastic.co/blog/why-license-change-AWS)
  * [Doubling Down on Open](https://www.elastic.co/blog/doubling-down-on-open)
  * [Doubling Down on Open, Part II](https://www.elastic.co/blog/licensing-change)
  * [Elastic License v2](https://www.elastic.co/blog/elastic-license-v2)
  * [FAQ on 2021 License Change](https://www.elastic.co/pricing/faq/licensing)
    * **Does this mean that Elasticsearch and Kibana are no longer Open Source? Yes.** Neither the Elastic License nor SSPL have been approved by the OSI, so to prevent confusion, we no longer refer to Elasticsearch or Kibana as open source. 
  * [old "open source" tier](http://web.archive.org/web/20201202235040if_/https://www.elastic.co/subscriptions) ("Apache 2.0: Now and always" 🙄) goes away
  * [The SSPL is not an open source license](https://opensource.org/node/1099)

* [OpenSearch](https://opensearch.org/) fork:
  * [Stepping up for a truly open source Elasticsearch](https://aws.amazon.com/blogs/opensource/stepping-up-for-a-truly-open-source-elasticsearch/)
  * [Introducing OpenSearch](https://aws.amazon.com/blogs/opensource/introducing-opensearch/)
  * [Truly Doubling Down on Open Source](https://logz.io/blog/open-source-elasticsearch-doubling-down/) @ logz.io
  * [FAQ](https://opensearch.org/faq)

* Third-party blogs, etc.
  * [Elasticsearch does not belong to Elastic](https://drewdevault.com/2021/01/19/Elasticsearch-does-not-belong-to-Elastic.html)
  * [Elasticearch and Kibana are now business risks](https://anonymoushash.vmbrasseur.com/2021/01/14/elasticsearch-and-kibana-are-now-business-risks)
  * [Is Elasticsearch no longer open source software?](https://opensourceconnections.com/blog/2021/01/15/is-elasticsearch-no-longer-open-source-software/)
  * [The Implications of Elasticsearch and Kibana License Change](https://www.globaldots.com/resources/blog/the-implications-of-elasticsearch-and-kibana-license-change-from-apache-2-0-to-sspl/)
  * [Let's talk about the Elastic license change](https://www.luminis.eu/blog/lets-talk-about-the-elastic-license-change/)
  * [Elastic is going closed-source. Where does that leave MSSPs?](https://logz.io/blog/elasticsearch-license-change-mssp/)

**Comment by petiepooo** [comment]
is it worth while making this an install-time option?  Could save some customization effort for those committed to Elastic or with existing Elastic license/infrastructure..

**Comment by mmguero** [comment]
@petiepooo in theory I like what you're saying, but in practice elastic is making that sort of thing difficult, as they've gone out of their way to break compatibility with clients and libraries that would allow a single project to support both without major effort:

* [Filebeat 7.13 is not compatible with elastichsearch-oss 7.10.2](https://github.com/elastic/beats/issues/25865)
  * [attempt to restore backwards compatibility rejected](https://github.com/elastic/beats/pull/26305#issuecomment-863472649)
* [Logstash always check elastic license pull request](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1005)
* [Elastic Hits Back at OpenSearch, Making Client Libraries Incompatible with Amazon-led Open Source Fork](https://wptavern.com/elastic-hits-back-at-opensearch-making-client-libraries-incompatible-with-amazon-led-open-source-fork)
* [Elastic beats Beats Users with a Breaking Change](https://logz.io/blog/breaking-change-to-beats-impacts-elasticsearch-elk-stack-users/)

I'm all for maintaining compatibility, and have to admit this whole thing makes me anxious as the gap between the products widens, but [by their own admission](https://www.elastic.co/pricing/faq/licensing#what-is-sspl-and-how-does-it-work), their new licensing schema cannot be referred to as "open source": 

> note that SSPL has not been approved by the OSI, so to avoid confusion we do not refer to it as an Open Source license.

and being an open source project is and will remain a major goal of Malcolm. It's for that reason that we've always only packaged the Apache 2.0 licensed components of elastic up until this point.

However, one thing I think we will be able to do for those with existing elastic infrastructure is allow Zeek logs to be forwarded to another Elasticsearch instance in addition to the dockerized OpenSearch instance that runs as part of the Malcolm cluster of containers (see the documentation, search for `ES_EXTERNAL_HOSTS`). This would at least allow the data to be available in your other existing infrastructure.

I'm open to ideas, but maintaining two separate branches of Malcolm to accommodate one open source license as well as the SSPL is something I just don't have the resources to do.

**Comment by petiepooo** [comment]
I can appreciate what you're saying, and agree that Elastic is the one misbehaving in their tussle with Amazon.

I am currently a big user of Security Onion.  They're using Elastic's basic license, and that has some features which I missed immediately upon accessing Malcolm.  Perhaps I'll see them or their equivalent again once the transition to Open Search is complete.

Are there situations where one might want to shutdown all the ancillary containers but leave the core OpenSearch stack (plus dependents like nginx) running, or vice versa?  I wonder if it makes sense to separate them into two docker-compose files; one for elk and one for everything else.  That would at least make it easier for someone looking to spin up bona fide Elastic, knowing it's stepping outside the recommended and supportable config.  It would also make it easier to maintain a fork that gives that capability.

**Comment by mmguero** [comment]
Thanks for the input. As I get ready to merge this branch, I'll make another pass through and try to allow for some of the internal scripts/configs that have to change for elastic vs. opensearch to be selectable via a switch or something. At least that would make it easier to maintain a downstream fork or custom config.

**Comment by mmguero** [comment]
For reference, here are the differences between the opensearch topic development branch and my main development branch:

https://github.com/mmguero-dev/Malcolm/compare/development...opensearch

**Comment by mmguero** [comment]
Looking at the comparison on the previous commit, I think trying to make a branch/fork that's compatible with both OpenSearch and ES is just going to take more resources than I'd be able to devote. While I understand and sympathize, it's just not something I want hanging over me everytime I have to make a change related to the underlying data stack.

That being said, I think it will be possible for someone who really needs to get this data into a non-open-source Elastic instance to set up forwarding from the logstash output (search `ES_EXTERNAL_HOSTS` in the readme)

**Comment by petiepooo** [comment]
Understood.  Thank you for giving it a serious consideration, @mmguero.
