### ISSUE TITLE
Bug: After uploading a pcap file, the dashboard and Arkime cannot function properly

### ISSUE THREAD

**Issue by pigcanfly432** [idaholab/Malcolm#545]
**Describe the bug**
Malcolm was originally working fine. After running `./scripts/wipe` ,restarting Malcolm, and uploading a pcap file, both the dashboard and Arkime are not functioning correctly. The error reports are as follows:

- Dashboards:

Displays the error message "Internal server error"
![Screenshot from 2024-08-21 14-24-16](https://github.com/user-attachments/assets/4937c9bd-ec26-472b-88d6-577c512cd192)

- Arkime:

Displays the error message {"success":false,"text":"User not found"}
![Screenshot from 2024-08-21 14-34-56](https://github.com/user-attachments/assets/9ba1e8a6-23de-4b65-82b1-5986257555ea)

**To Reproduce**
1. `./scripts/wipe`
2. `./scripts/start`
3. upload the pacp file
4. click dashboards or arkime
5. See error

**Expected behavior**

The dashboard and Arkime should display their content normally.

**Malcolm Version:**
[Malcolm v24.07.0]

**How are you running Malcolm?**
The installation was performed according to the official documentation.
 [ubuntu 22.04](https://malcolm.fyi/docs/ubuntu-install-example.html#InstallationExample)

**Additional context**

device info

- Memory: 16 GB
- CPUs:  4 Core

Memory is allocated for OpenSearch and Logstash as follows:
memory is allocated for opensearch and logstash
> doris@doris:~/Malcolm$ grep JAVA_OPTS config/*.env
config/logstash.env:LS_JAVA_OPTS=-server -Xmx2500m -Xms2500m -Xss1536k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true
config/opensearch.env:OPENSEARCH_JAVA_OPTS=-server -Xmx10g -Xms10g -Xss256k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true

**Comment by mmguero** [comment]
I've just released Malcolm v24.08.0 and I cannot reproduce this problem, but I couldn't reproduce it in v24.07.0. Is there anything in the output of `./scripts/logs` when you get the internal server error that could help us narrow it down?

**Comment by mmguero** [comment]
No response from OP, closing.
