### ISSUE TITLE
Missing cracklib-runtime package prevents password from being updated by non-root user

### ISSUE THREAD

**Issue by lenzc-pasco-wa** [idaholab/Malcolm#548]
**Describe the bug**
A missing password dictionary prevents the user from changing their own password after initial installation.

**To Reproduce**
1. Install sensor with easy to type/remember password.
2. Try to reset password from bash with passwd
3. After meeting the password requirements, receive error about missing cracklib dictionary.

**Expected behavior**
The user should be able to change the password without needing to escalate to root to bypass the password checking requirements. The [documentation](https://idaholab.github.io/Malcolm/docs/hedgehog-hardening.html#HedgehogHardening) states that Malcolm/Hedgehog uses libpam-pwquality instead of libpam-cracklib.

**Screenshots and/or Logs **
If applicable, attach screenshots or container logs (e.g., the relevant bits of `./scripts/logs`) to help explain your problem.
![image](https://github.com/user-attachments/assets/24840825-e829-4d08-b02e-ff5f341b034a)

**Malcolm Version:**
 - Version 24.07.0

**How are you running Malcolm?**
- [X] [ISO installed](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) (on VM or dedicated hardware)
- [ ] via [Docker](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) on [Linux](https://idaholab.github.io/Malcolm/docs/host-config-linux.html#HostSystemConfigLinux)
- [ ] via Docker on [Microsoft Windows](https://idaholab.github.io/Malcolm/docs/host-config-windows.html#HostSystemConfigWindows)
- [ ] via Docker on [macOS](https://idaholab.github.io/Malcolm/docs/host-config-macos.html#HostSystemConfigMac)
- [ ] via [Kubernetes](https://idaholab.github.io/Malcolm/docs/kubernetes.html#Kubernetes) (please provide platform details: e.g., on-prem K3s, Amazon AWS EKS, Microsoft Azure AKS, etc.)
- [ ] other (please describe)

**Additional context**

**Comment by mmguero** [comment]
Thanks

**Comment by mmguero** [comment]
v24.08.0 should be released today which will rectify this, thanks again.
