### ISSUE TITLE
Does Malcolm support the use of remote logstash instances？

### ISSUE THREAD

**Issue by alleniverson33** [idaholab/Malcolm#549]
If Inscribe

**Comment by mmguero** [comment]
I'm not sure what that would buy you, as that would skip all of the enrichment that's in Malcolm's logstas pipeline. Malcolm maintains its own internal logstash instance, which in-turn can forward to its own local OpenSearch instance or a remote [OpenSearch or Elasticsearch instance](https://idaholab.github.io/Malcolm/docs/opensearch-instances.html#OpenSearchInstance).

On the other hand, if your question is whether or not the Hedgehog Linux sensor can forward Zeek/Suricata logs to another logstash instance that's not Malcolm, then yes I suppose it could be [configured to do so](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#Hedgehogfilebeat).

**Comment by alleniverson33** [comment]
Thanks for you answer
