### ISSUE TITLE
The ```install.py``` script doesn't update ```sysctl.conf```

### ISSUE THREAD

**Issue by Gandalf098** [idaholab/Malcolm#55]
the title says it all, as alternative though follow the instructions manually in the repo to change limits and sysctl.conf

also the script runs without root or sudo permissions

**Comment by mmguero** [comment]
Could you give me the contents of your `/etc/os-release` (and/or `/etc/*-release` if there are others), `/etc/issue`. It could be that it's not detecting your system correctly.
