### ISSUE TITLE
main-arm64 Format string python3

### ISSUE THREAD

**Issue by jbc22** [idaholab/Malcolm#562]
**Describe the bug**
When starting zeek:arm-64 (version 4256b0eea590) as a container in Podman, the container shuts down immediately after throwing an error:

`usermod: no changes
root
uid=0(root) gid=0(root) groups=0(root)
Error: Format string 'python3 /usr/local/bin/pcap_zeek_processor.py %(ENV_PCAP_PIPELINE_VERBOSITY)s\n--start-sleep 10\n--threads %(ENV_ZEEK_AUTO_ANALYZE_PCAP_THREADS)s\n--publisher "%(ENV_PCAP_MONITOR_HOST)s"\n--pcap-directory /pcap/processed\n--node "%(ENV_PCAP_NODE_NAME)s"\n--zeek /opt/zeek/bin/zeek-offline\n--extra-tags "%(ENV_EXTRA_TAGS)s"\n--autotag "%(ENV_AUTO_TAG)s"\n--autozeek "%(ENV_ZEEK_AUTO_ANALYZE_PCAP_FILES)s"\n--forcezeek "%(ENV_ZEEK_ROTATED_PCAP)s"\n--extract "%(ENV_ZEEK_EXTRACTOR_MODE)s"\n--zeek-directory /zeek/upload' for 'program:pcap-zeek.command' contains names ('ENV_EXTRA_TAGS') which cannot be expanded. Available names: ENV_AUTO_TAG, ENV_BUILD_DATE, ENV_CCACHE_COMPRESS, ENV_CCACHE_DIR, ENV_DEBIAN_FRONTEND, ENV_DEFAULT_GID, ENV_DEFAULT_UID, ENV_HOME, ENV_HOSTNAME, ENV_LC_CTYPE, ENV_MAIL, ENV_MALCOLM_VERSION, ENV_PATH, ENV_PCAP_FILTER, ENV_PCAP_IFACE, ENV_PCAP_IFACE_TWEAK, ENV_PCAP_MONITOR_HOST, ENV_PCAP_NODE_NAME, ENV_PCAP_PIPELINE_VERBOSITY, ENV_PGROUP, ENV_PUSER, ENV_PUSER_CHOWN, ENV_PUSER_PRIV_DROP, ENV_PWD, ENV_PYTHONDONTWRITEBYTECODE, ENV_PYTHONUNBUFFERED, ENV_SHLVL, ENV_SUPERCRONIC_CRONTAB, ENV_SUPERCRONIC_URL, ENV_SUPERCRONIC_VERSION, ENV_TERM, ENV_USER, ENV_VCS_REVISION, ENV_ZEEK_AUTO_ANALYZE_PCAP_FILES, ENV_ZEEK_AUTO_ANALYZE_PCAP_THREADS, ENV_ZEEK_CUSTOM_PATH, ENV_ZEEK_DIR, ENV_ZEEK_DISABLE_BEST_GUESS_ICS, ENV_ZEEK_DISABLE_HASH_ALL_FILES, ENV_ZEEK_DISABLE_LOG_PASSWORDS, ENV_ZEEK_DISABLE_SPICY_IPSEC, ENV_ZEEK_DISABLE_SPICY_LDAP, ENV_ZEEK_DISABLE_SPICY_OPENVPN, ENV_ZEEK_DISABLE_SPICY_QUIC, ENV_ZEEK_DISABLE_SPICY_STUN, ENV_ZEEK_DISABLE_SPICY_TAILSCALE, ENV_ZEEK_DISABLE_SPICY_TFTP, ENV_ZEEK_DISABLE_SPICY_WIREGUARD, ENV_ZEEK_DISABLE_SSL_VALIDATE_CERTS, ENV_ZEEK_DISABLE_STATS, ENV_ZEEK_DISABLE_TRACK_ALL_ASSETS, ENV_ZEEK_EXTRACTOR_MODE, ENV_ZEEK_EXTRACTOR_PATH, ENV_ZEEK_INTEL_FEED_SINCE, ENV_ZEEK_INTEL_FEED_SSL_CERTIFICATE_VERIFICATION, ENV_ZEEK_INTEL_ITEM_EXPIRATION, ENV_ZEEK_INTEL_PATH, ENV_ZEEK_INTEL_REFRESH_CRON_EXPRESSION, ENV_ZEEK_INTEL_REFRESH_ON_DEPLOY, ENV_ZEEK_INTEL_REFRESH_ON_ENTRYPOINT, ENV_ZEEK_INTEL_REFRESH_THREADS, ENV_ZEEK_LIVE_CAPTURE, ENV_ZEEK_PCAP_PROCESSOR, ENV_ZEEK_ROTATED_PCAP, ENV_ZEEK_SYNCHROPHASOR_DETAILED, ENV_ZEEK_THIRD_PARTY_PLUGINS_GREP, ENV_ZEEK_THIRD_PARTY_SCRIPTS_GREP, ENV_ZEEK_VERSION, ENV_container, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:pcap-zeek' (file: '/etc/supervisord.conf')
For help, use /usr/bin/supervisord -h`

**To Reproduce**
1. Open Podman
2. Click on 'Images'
3. Click on 'Pull'
4. Enter "ghcr.io/idaholab/malcolm/zeek:main-arm64" in Image to Pull and click "Pull Image"
5. Click Done
6. Click Start Container for zeek main-arm64
7. Accept default values on the "Run Image" page and click "Start Container"
8. Navigate to "Logs"
9. See error

**Expected behavior**
At step 8 above, I expect to have a tty session to the container.

**Screenshots and/or Logs **
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/c83cfa28-9e28-42da-935b-af79d826ea0d">

**Malcolm Version:**
(sha256:36633a755fde50af2b2c0a7e1781221df381a5903217500fe2b47b6f8d1b2340)

**How are you running Malcolm?**
- [ ] [ISO installed](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) (on VM or dedicated hardware)
- [ ] via [Docker](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#InstallationExample) on [Linux](https://idaholab.github.io/Malcolm/docs/host-config-linux.html#HostSystemConfigLinux)
- [ ] via Docker on [Microsoft Windows](https://idaholab.github.io/Malcolm/docs/host-config-windows.html#HostSystemConfigWindows)
- [ ] via Docker on [macOS](https://idaholab.github.io/Malcolm/docs/host-config-macos.html#HostSystemConfigMac)
- [ ] via [Kubernetes](https://idaholab.github.io/Malcolm/docs/kubernetes.html#Kubernetes) (please provide platform details: e.g., on-prem K3s, Amazon AWS EKS, Microsoft Azure AKS, etc.)
- [ x ] other (please describe): Podman on MacOS M2 chip

**Additional context**

**Comment by mmguero** [comment]
Podman's not supported yet, but we're [working on it](https://github.com/idaholab/Malcolm/issues/407). I'm not going to chase this down until that's happening. At first glance, though, it looks like supervisord is missing some of the [environment variables](https://idaholab.github.io/Malcolm/docs/malcolm-config.html#MalcolmConfigEnvVars). I'd recommend checking the [docker-compose](https://github.com/idaholab/Malcolm/blob/1b5e003023aa0b876dc100f8def0645ada8283c2/docker-compose.yml#L446-L563) file for whatever the .env files are that that container needs, and make sure you've set them [as described in the documentation](https://idaholab.github.io/Malcolm/docs/malcolm-hedgehog-e2e-iso-install.html#MalcolmConfig).

Once the podman support is done and built into the [control scripts](https://idaholab.github.io/Malcolm/docs/running.html#Starting), also note that the supported way for starting and stopping malcolm is to use the control scripts.

I'm going to close this issue for now, but once podman is supported if things are still broken feel free to reopen.
