### ISSUE TITLE
Allow Hedgehog build for Raspberry Pi 5

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#569]
Currently the hedgehog for raspberry pi build only supports pi 4. We should look to see if a pi 5 build has any issues, I doubt there would be.

**Comment by w3rew0lf** [comment]
I tried using the pi 4 image on a pi 5, initially it showed bcm2712-rpi-5-b.dtb. hence when I added the file to boot partition the screen goes blank with Constant ACT light. can I use the sensor_install.sh to install things on a pi os ?

**Comment by mmguero** [comment]
I don't think you'll be able to use the sensor_install.sh directly to install on an existing Pi OS installation, no, but you could use it as a basis for figuring out the commands yourself.

**Comment by mmguero** [comment]
I'm not sure yet this is possible:

See the [FAQ on the debian wiki](https://raspi.debian.net/faq/):

> When will there be support for the RPi5?
> 
> We need mainline Linux to be able to boot on a device before trying to support it in Debian. The Raspberry 5 family boots with a kernel that has many components not yet in mainline. We cannot plan for including RPi5 support at least until regular, upstream, mainline Linux kernels are able to boot on it.
> 

This was written a while ago, though, so I'll investigate.

**Comment by mmguero** [comment]
See also [this thread](https://lists.debian.org/debian-arm/2024/03/msg00009.html) as of 5 Mar 2024.

**Comment by mmguero** [comment]
From everything I can tell this is not yet possible due to the missing upstream Kernel support.

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/376)
