### ISSUE TITLE
implement paging for extracted files download dialog

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#595]
We should implement paging in the [extracted_files_http_server.py](https://github.com/idaholab/Malcolm/blob/main/shared/bin/extracted_files_http_server.py). 

Pick something like a page size of 50 and have next/previous buttons at the bottom or top.

**Comment by jjrush** [comment]
I have this implemented and tested on a branch in my fork. Will work to get it added to a future release.

**Comment by mmguero** [comment]
> I have this implemented and tested on a branch in my fork. Will work to get it added to a future release.

Thanks, just submit a PR to this repo and I'll get it staged for v24.11.0.

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/361)
