### ISSUE TITLE
Videos or verbose walkthroughs for Malcolm upgrades

### ISSUE THREAD

**Issue by ee-hex-ee** [idaholab/Malcolm#608]
**For what topic would you like to see training developed?**
Persistent deployments of Malcolm do not prefer the "blow it away and start fresh" instance commonly employed. 

**What format would be best suited for this training?**
Video is preferred but a verbose written guide that expands on the current documentation could suffice. 

**Is there existing [Malcolm documentation](https://idaholab.github.io/Malcolm/) that could be improved by including this topic?**
https://malcolm.fyi/docs/malcolm-upgrade.html#UpgradePlan 

**Additional context**
Feedback is that most users attempting to upgrade have not had success with current documentation and also cannot tell what method is best for them even if it seems obvious.

**Comment by mmguero** [comment]
The reason the documentation isn't good is because the upgrade process itself isn't very good. 😬

**Comment by mmguero** [comment]
See #609 and #610

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/353)
