### ISSUE TITLE
not parsing Profinet Real-Time Protocol directly on ethernet frame

### ISSUE THREAD

**Issue by Thomislav** [idaholab/Malcolm#61]
Hello, i have PCAP files from tapping Profinet-Communication with wireshark/tshark. After Uploading it to Malcolm i mainly see S7Comm and cotp. The Documentation mentions zeek is able to parse Profinet but it doesn't work. see attached file.
![image](https://user-images.githubusercontent.com/84561792/137637683-53a7ab08-ba27-4467-a53a-15a3289a1b67.png)
In wireshark it says Profinet Real-Time Protocol thats directly on the Ethernet-Frame. see second file.
![image](https://user-images.githubusercontent.com/84561792/137637765-e771c5be-2bc9-4350-ab62-caf09ed6850a.png)
I havent found Data in the Elasticsearch database containing any ethernet information. Does zeek not parse ethernet information or am i doing something wrong?

**Comment by Thomislav** [comment]
Thank you for the quick reply. unfortunately i am not allowed to post such data. it is good to know that there could be such a function in the future.

**Comment by mmguero** [comment]
No problem. For now I'll keep this issue open so we can track it, though it may not be resolved in the short term.

**Comment by mmguero** [comment]
Kamino closed and cloned this issue to [cisagov/Malcolm](https://github.com/cisagov/Malcolm/issues/484)
