### ISSUE TITLE
docker-compose | "function" has no attribute "get" (ubuntu 20.04 install)

### ISSUE THREAD

**Issue by 73F0SG1R** [idaholab/Malcolm#94]
vanilla ubuntu 20.04 install fail - following "https://github.com/idaholab/Malcolm#InstallationExample", using install.py from "https://github.com/idaholab/Malcolm/releases/tag/v5.2.11" (latest)

...
"docker-compose version" failed, attempt to install docker-compose? (Y/n): y

Install docker-compose directly from docker github? (Y/n): y
AttributeError: 'function' object has no attribute 'get'

**Comment by mmguero** [comment]
Thanks, I'll post an update to `install.py` on the `main` branch here shortly.

**Comment by mmguero** [comment]
Thanks for the report, idaholab/Malcolm@15562fb2ba59e6dbd248901e36b98c874bc68e9b has the fix. I've also updated the v5.2.11 release here on GitHub with the fixed `malcolm_common.py` file.
